- client/examples/multiple.html
- client/examples/single.html
- client/src/api.ts
- client/src/lib.js
- client/test/lib.spec.js
- client/test/run.js
* Fixes the status and delete endpoint URLs
* Removes the CID dependency, as it currently doesn't work with multiformats/cid on unpkg (https://unpkg.com/multiformats@4.5.3/cid?module)
* Adds a couple of examples for storing files and querying their status
> fix: client fixes, tweaks and examples

- site/src/bindings.d.ts
- site/src/index.js
- site/src/routes/metrics.js
This PR adds MVP prometheus metrics reporting. It adds a `/metrics` endpoint that renders metrics in prometheus exposition format.
Due to the KV format we have to read every nft and deal to collect metrics. Since the size of the data is small right now it doesn't take long. The result is cached by cloudflare for 10 minutes.
It gives us the ability to build graphs for monitoring and alerting in Grafana:
> feat: prom metrics

- site/src/utils/utils.js
If you use a token that has been deleted then you'll get a "Session expired" message. There are no "sessions" with tokens so this is misleading.
fixes #48
> fix: error message for deleted token

- client/src/lib.js
- client/test/lib.spec.js
Not passing the token means you get a `Bearer undefined` header sent to the server and it responds with `Error: token must have 3 parts`.
The PR just checks the token is not falsey and throws with a "missing token" error if it is.
> fix: validate token existence client side

- README.md
- site/src/bindings.d.ts
- site/src/cluster.js
- site/src/constants.js
- site/src/index.js
- site/src/jobs/metrics.js
- site/src/jobs/pins.js
- site/src/models/metrics.js
- site/src/routes/metrics.js
- site/src/utils/utils.js
- site/wrangler.toml
This PR adds cron jobs for metrics generation and pin status / size tracking.
Previously the metrics were counted when the user hit the `/metrics` endpoint and then cached for 10 minutes. Now they are counted and stored in a new KV "METRICS". The `/metrics` endpoint has been updated to just read the latest values from the KV store.
The code to count metrics has also been updated to count filecoin deals in the "DEALS" KV, which resolves https://github.com/ipfs-shipyard/nft.storage/issues/59
There was a hack in the `/metrics` endpoint that was updating pin status and size for NFTs that were stored via the pinning services API. This has been pulled out into it's own dedicated cron job.
> feat: cron jobs for metrics and pin status tracking

- site/src/pinata.js
- site/src/routes/nfts-upload.js
- site/src/routes/pins-add.js
- site/src/routes/pins-replace.js
This endpoint now supports CBOR data.
Also adds try/catch around calls to prevent response being sent early on failure.
> refactor: switch to Pinata pinByHash

- site/src/models/nfts.js
This means we're doing a lot more unnecessary work currently in the followup cron task.
> fix: store NFT metadata when NFT is new

- site/src/utils/auth.js
Instead of:
```
Magic Admin SDK Error: [EXPECTED_BEARER_STRING] Expected argument to be a string in the `Bearer {token}` format.
```
> fix: better error message for missing auth token

- site/package.json
- site/pw-test.config.js
- site/src/bindings.d.ts
- site/src/constants.js
- site/src/pinata-psa.js
- site/src/pinata.js
- site/test/nfts-check.spec.js
- site/test/scripts/events.js
- site/test/scripts/helpers.js
- site/test/scripts/node-globals.js
- site/test/scripts/worker-globals.js
- site/test/version.spec.js
- site/tsconfig.json
Adds e2e tests for the API, using playwright.
Eventually the following repeated lines in tests will be replaced:
```js
const request = new Request(`http://localhost/check/${cid}`)
const event = new TestFetchEvent('fetch', { request })
globalThis.dispatchEvent(event)
const res = await event.respondWithPromise
```
...with a call to `fetch` when playwright supports service workers (currently only regular workers):
```js
const res = await fetch(`http://localhost/check/${cid}`)
```
Later, these same tests can be run against a real life deployed API on Cloudflare.
resolves #96
> test: site tests

- packages/api/src/routes/metrics.js
- packages/cron/src/bin/metrics.js
- packages/cron/src/jobs/metrics.js
🤦‍♂️ I realised the "queued" pins metric is already effectively tracking this and so a separate metric for this is not needed (and is using a substantial amount of our rate limited api requests to do so).
> revert: collection of followup metrics

- packages/client/README.md
- packages/website/pages/index.js
refs https://github.com/ipfs-shipyard/nft.storage/issues/115
> docs: change JS client docs to use metadata API

- packages/client/package.json
- update homepage url
- add reportistory object with directory
see: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository
License: MIT
> chore: fix client repo link on npm listing

- package.json
- yarn.lock
- force yarn to install url-regex-safe@^2.0.2 to avoid pulling in a version of re2 that won't compile on node 16
- avoid deprecated url-regex-safe@1.1.0 which was previously pinned
From local testing, the problem is caused by yarn's dependency resolution pulling in deprecated modules. The direct dep `get-urls` builds fine on node 16 unchaged under npm, but fails under yarn, as npm does not included deprecated versions in its resolution.
`<grumble>`why are we using yarn? this always happens.`</grumble>`
Fixes #160 
License: MIT
> chore: avoid deprecated url-regex-safe version

- README.md
- packages/api/README.md
- packages/api/src/constants.js
- packages/website/README.md
* Moves `api` and `website` getting started documentation into the proper directories
* Adds overview documentation to the README at the root and instructions for running locally
> docs: cleanup docs and move into proper places

- packages/website/package.json
get yarn workspace to symlink in nft.storage from the local workspace by making the dependency version range match.
License: MIT
> chore: ensure website uses local client

- .github/workflows/api.yml
- .github/workflows/client.yml
- .github/workflows/cron-metrics.yml
- .github/workflows/cron-pinata.yml
- .github/workflows/cron-pins.yml
- .github/workflows/deploy.yml
- .github/workflows/release.yml
- .github/workflows/website.yml
update all workflows to use:
- actions/setup-node@v2 with `node-version: 16`
- actions/checkout@v2
- bahmutov/npm-install@v1
License: MIT
> chore: use node 16 in CI

- packages/client/package.json
Fix local `npm install` in a project that doesn't have `npm-run-all` installed. I think because we're using `prepare` "Runs on local npm install without any arguments" (https://docs.npmjs.com/cli/v6/using-npm/scripts).
This PR switches to use **`prepublishOnly`**.
> fix(client): npm lifecycle build command

- packages/client/src/lib/interface.ts
The deal data selector is now available so if folks actually want to retrieve data from Filecoin they'll soon be able to use this (🔜 currently needs custom lotus client filecoin-project/lotus#6393).
@ribasushi can you confirm this is just for "active" and "terminated" deals?
resolves #192
> feat: deal data selector

- packages/api/package.json
- packages/api/src/cluster.js
- packages/api/src/routes/nfts-upload.js
- packages/api/test/mocks/cluster/get_pins#@cid.js
- packages/client/src/lib.js
- packages/client/test/lib.spec.js
- packages/cron/package.json
- yarn.lock
* Uses `local` option for Cluster when file is >2.5MB (size recommended by @hsanjuan). This causes cluster to add blocks to the local node only (instead of sending to all cluster nodes) and relies on bitswap to efficiently distibute the blocks asyncronously. It allows the request to complete sooner and speeds up uploads significantly.
* Uses `transform` from `streaming-iterables` instead of `parallelMap`. The `parallelMap` function is actually a parallel batch, so if 1 of the 3 concurrent requests stalls and the other 2 complete then we have to wait before starting a new batch of 3.
* Does not assume pinned status after file upload to Cluster - when creating the pin, Cluster is checked for status (resolves https://github.com/ipfs-shipyard/nft.storage/issues/191)
* Changes `MAX_CHUNK_SIZE` …
> fix: chunking issues

- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- yarn.lock
This resolves type errors for folks wishing to pass a `CarIndexedReader` to `storeCar`.
`CarIndexedReader` does not extend the `CarReader` class but they both implement `RootsReader` and `BlockReader`...and these are the interfaces carbites needs.
https://github.com/ipld/js-car/blob/da397a8b3659a3e3ead9411746962885537ec1ac/api.ts#L49
> fix: the CarReader type is a collection of interfaces

- package.json
I propose we remove pre-push hook. Often times it test things I have not changed and just gets in the way. I find myself using `--no-verify ` a lot.
We also run tests in pulls and pushes which is free of env bias. So I propose we remove this and just lean on CI before merging things.
> chore: remove pre-push hook

- packages/api/package.json
- packages/cron/package.json
- yarn.lock
We think this will fix a sproadic error we are seeing adding CARs to cluster in nft.storage.
> fix: set stream-channels=false for cluster add

- .github/workflows/migration-2021-08-18.yml
- packages/database/src/config.js
- packages/database/src/migrations/2021-08-18-token-asset-queue.js
Followup for #278 to go over all existing TokenAsset records and create pointers to it from corresponding queues
> feat: migrate status index to task queue

- packages/website/package.json
uploading via website fails with ipfs-car>=0.5 (you get an empty dir with cid `bafybeiczsscdsbs7ffqz55asqdf3smv6klcw3gofszvwlyarci47bgf354` for all uploads). Rolling back as a quick fix.
License: (Apache-2.0 AND MIT)
> fix: pin ipfs-car verion to avoid empty upload issue

- packages/website/pages/index.js
- packages/website/pages/terms.js
- Removes the remote pinning service box from the homepage:
- Removes all the "Beta" information from the website  
Closes #365
Closes #366
> feat: remove pinning service from the homepage

- packages/client/README.md
Fixes the examples link, and adds direct links to the node and browser subdirs. Closes #396
> fix link to examples directory in client docs

- README.md
@filipepolizel created an nft.storage client for unity! This PR adds a link to it from the README.
> docs: add unity client library link

- packages/api/README.md
- packages/api/wrangler.toml
* `usage_model` cannot be overridden if set at top level and for dev we shouldn't need to setup a paid account.
* Added `DATABASE_URL` in the right places in the config (vars are not inherited).
* Split out vars in mine and @gozala's sections to be consistent with the staging/prod config.
* Removed `type = "webpack"` from mine and @gozala's sections so we inherit `type = "javascript"`.
Useful info on config: https://developers.cloudflare.com/workers/cli-wrangler/configuration
> fix: remove usage_model from top level

- packages/api/wrangler.toml
- packages/website/components/button.js
- packages/website/components/footer.js
- packages/website/components/hero.js
- packages/website/components/navbar.js
- packages/website/lib/countly.js
- packages/website/lib/types.d.ts
- packages/website/next.config.js
- packages/website/package.json
- packages/website/pages/404.js
- packages/website/pages/_app.js
- packages/website/pages/files.js
- packages/website/pages/index.js
- packages/website/pages/login.js
- packages/website/pages/manage.js
- packages/website/pages/new-file.js
- packages/website/pages/new-key.js
This PR adds countly analytics for tracking usage of the website.
I used the same setup from Web3 Storage.
You can check the new Countly app and dashboard for the stats generated while developing this.
TODO:
Closes #360
> chore: setup countly analytics

- packages/niftysave/src/migrate/nft-asset.js
use view so that batch inserts would work. Works around https://github.com/hasura/graphql-engine/issues/4633
> fix: nft-asset migration

- packages/niftysave/package.json
- packages/niftysave/src/migrate/erc721-import.js
Disable batching for erc721-import table because fauna has many duplicates
> Fix: niftysave erc721 import migration

- packages/api/src/routes-v1/nfts-list.js
- packages/api/src/routes-v1/pins-list.js
- packages/api/test/nfts-list-v1.spec.js
This PR adds minimum, maximum and default limits for v1 list endpoints.
The default is the same - 10. I upped the max from 100 to 1,000, which should be a non-breaking change. Minimum remains at 1...
> fix: min, max and default limits for v1 list endpoints

- packages/api/db/tables.sql
Sister PR to https://github.com/ipfs-shipyard/nft.storage/pull/494 which can get merged and deployed now making updating to use the new cluster easier later.
> feat: add new cluster enum and nothing else

- packages/api/src/index.js
- packages/api/src/routes-v1/metrics.js
- packages/api/test/nfts-list-v1.spec.js
- packages/tools/cf-sync/push-to-db.js
Not exporting byte totals anymore as these can come from dagcargo.
Have split upload totals out by type.
Have split pin totals by service and status (as opposed to just status).
Example output:
```
nftstorage_users_total 1
nftstorage_uploads_total{type:"Car"} 0
nftstorage_uploads_total{type:"Blob"} 0
nftstorage_uploads_total{type:"Multipart"} 0
nftstorage_uploads_total{type:"Remote"} 0
nftstorage_uploads_total{type:"Nft"} 0
nftstorage_pins_total{service:"Pinata",status:"PinQueued"} 0
nftstorage_pins_total{service:"Pinata",status:"Pinning"} 0
nftstorage_pins_total{service:"Pinata",status:"Pinned"} 0
nftstorage_pins_total{service:"Pinata",status:"PinError"} 0
nftstorage_pins_total{service:"IpfsCluster",status:"PinQueued"} 0
nftstorage_pins_total{service:"IpfsCluster",status:"Pinning"} 0 …
```
> feat: add prom metrics endpoint generated from postgres data

- packages/api/src/errors.js
- packages/api/src/index.js
- packages/api/src/middleware/psa.js
- packages/api/src/routes-v1/pins-add.js
- packages/api/src/routes-v1/pins-delete.js
- packages/api/src/routes-v1/pins-get.js
- packages/api/src/routes-v1/pins-list.js
PSA error responses are not like nft.storage API responses. This PR adds middleware to intercept thrown errors and respond with an object in the shape expected for PSA responses.
> feat: add PSA error handler

- packages/client/examples/browser/store.html
The log function accepts just one parameter, so the data wasn't actually printed.
This commit fixes it
> Fixed log in store.html example

- packages/website/public/schema.yml
The limit was recently upped to 1,000 from 100 as we now use a database that can handle this load. The change was not reflected in the OpenAPI docs.
refs https://github.com/nftstorage/nft.storage/issues/754
> fix: list API maximum limit value

- packages/website/public/schema.yml
I started to add a note about content types to the API docs, but it seems that the `/store` endpoint wasn't in the schema, just `/upload`. 
So this adds docs for the `/store` endpoint based on what I could glean from the code. Someone should probably look it over to make sure it's correct.
May need some formatting tweaks and so on - I wasn't able to run the website build locally, since my env isn't set up, so I haven't seen it rendered yet.
Also closes #490 - we actually allow all file types now, but I added a recommendation to only use images for the `image` field.
> chore: add /store endpoint to API schema

- packages/client/examples/node.js/encodeBlob.js
- packages/client/examples/node.js/package.json
Auto chunking for CAR files shipped https://github.com/nftstorage/nft.storage/pull/588 and I created an example so I could test it out myself manually. May as well PR it for others to see.
> docs: add encodeBlob example

- packages/website/public/schema.yml
Previously these did not specify that each part should have the name "file".
> fix: better docs for multipart requests

- packages/client/package.json
- packages/client/test/mock-server.js
- yarn.lock
This moves to the new v3 @web-std modules so is a breaking change.
resolves https://github.com/nftstorage/nft.storage/issues/742
> chore!: update dependencies

- packages/database_v2/migrations/default/1637710727281_improve_batchify_processor_hanging/up.sql
The batch processor was hanging for a long time even though the timer stated it was running in a matter of a few milliseconds and this was due to an inefficient select statement in the readout I was using to measure it.
Was also using this as a succinct issue to onboard @ice-breaker-tg demonstrate how Hasura migrations work
> fix (niftsave): fixes hanging batch process in sql

- packages/api/src/utils/debug.js
- packages/client/src/lib.js
Adds an `X-Client` header to the JS client and configures Sentry to accept it.
Closes https://github.com/nftstorage/nft.storage/issues/57
> feat: add X-Client header

- packages/client/package.json
- packages/client/rollup.esm.config.js
- yarn.lock
I didn't realise this didn't exist yet for nft.storage.
Now that we're pulling in more dependencies, and dependencies that are incompatible wth webpack4 and skypack we need a way for people to import the code in bundlers and on the browser.
After merge, webpack4 users should be able to:
```js
import { NFTStorage } from 'nft.storage/dist/bundle.esm.min.js'`
```
...and directly in the browser like;
```js
import { NFTStorage } from 'https://cdn.jsdelivr.net/npm/nft.storage/dist/bundle.esm.min.js'
```
refs https://github.com/nftstorage/nft.storage/issues/876
> fix: add prebuilt bundle

- packages/client/package.json
🤦‍♂️ is being generated but not included in the files sent to npm.
> fix: include bundle in npm files

- packages/client/rollup.esm.config.js
Without this option, we get `import require$$0 from"buffer";` in the bundle, which cannot be resolved when used in the browser (what it is for).
> fix: do not prefer node.js builtins

- packages/website/public/schema.yml
This adds a note about the 100MiB size limit to the `store` and `upload` endpoints in the API schema.
Closes #832
> chore(website): add info about size limits to http api docs

- packages/api/src/errors.js
- packages/api/src/routes/metaplex-upload.js
Adds `ErrorMetaplexTokenNotFound` and `ErrorInvalidMetplexToken` error types and uses them in place of `HTTPError` in the metaplex route handler. Closes #859
I left the errors in the `validate` method alone, since those should only occur if we're missing configuration on the backend and can't be triggered by user input.
> fix: use custom error types for metaplex errors

- packages/api/src/constants.js
- packages/api/src/routes/metaplex-upload.js
This stores the value of the `METAPLEX_AUTH_TOKEN` global in `secrets.metaplexAuth` in constants.js to be more consistent with the rest of the code.
> chore(api): add METAPLEX_AUTH_TOKEN to constants.js

- packages/api/db/docker/docker-compose.yml
My M1 Mac wasn't able to run the API tests because the `postgrest` image didn't have an ARM variant, and it wasn't working with the X86 emulation. Just yesterday though, v9.0.0 was released and an ARM variant was published to docker hub.
Now I can run the tests locally instead of pushing a bunch of "fix test (for real this time)" commits up to CI 😛
> chore(api): update postgrest docker image to v9.0.0

- packages/client/package.json
`@ipld/dag-cbor` is directly used in src/token.js, so it should be a dependency, not a devDependency. This fixes an error that yarn pnp raises due to accessing an undeclared dependency.
> fix: make @ipld/dag-cbor a dependency of nft.storage

- packages/website/pages/index.js
I am not sure if npm is case sensitive in all cases, but the incorrect case caused the issue for me at least.
The correct line to install npm package is:
`npm install nft.storage`
not:
```
$ npm install NFT.Storage
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/NFT.Storage - Not found
npm ERR! 404 
npm ERR! 404  'NFT.Storage@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
> fix: install instructions

- packages/api/src/cluster.js
When a bad request happens with an empty multipart form, we should return 400 Error instead of 500. This was resulting in alerts for bad usage to be filled in in Sentry and alerts being triggered
> fix: error code for empty multipart data

- packages/client/package.json
chore: updated dag to to not be restricted
Fixes #950 unlocks the version of @ipld/dag-json
> chore: updated dag to to not be restricted

- PEERS
A list of known IPFS peers that are hosting content uploaded to NFT.Storage.
YOU DO NOT NEED THIS LIST. All peers that provide content on IPFS are
discoverable via the DHT. IPFS transfers content P2P from multiple sources
including other peers that recently acquired the content.
Note: this list may be incorrect, may change, or become out of date at any
time without notice.
refs #1000
> feat: add list of known peers hosting content for nft.storage

- packages/api/README.md
- packages/api/src/bindings.d.ts
- packages/api/src/constants.js
- packages/api/src/errors.js
- packages/api/src/index.js
- packages/api/src/middleware/psa.js
Here's a MVP for an allowlist for the pinning service API. Set a global var called `PSA_ALLOW` with user IDs (CSV) of users allowed to use the API. If the variable is not set we allow everyone.
resolves https://github.com/nftstorage/nft.storage/issues/319
resolves https://github.com/nftstorage/nft.storage/issues/148
> feat: psa allowlist

- packages/client/examples/node.js/old-cidv0.js
- packages/client/examples/node.js/package.json
`ipfs-car@0.6.1` now supports the `rawLeaves` option.
It means that if absolutely necessary, a v0 CID can be obtained for a DAG by downgrading the CID returned from the library (note this is only possible by using `rawLeaves: false`).
How far do we want to go with this? We could stop here, or we could add it as an option to the client that `encodeDirectory` and `encodeBlob` might take - the example becomes simplier but we'll need to release a new version of the client. My gut instinct is to leave it like this.
> docs: add cidv0 example

- packages/website/pages/blog/post/[slug].js
- packages/website/posts/2022-01-05-mikeal-modern-finance.mdx
addresses #1040
will center position the blog images and prevent them from automatically being 100% if the desired width is not added to avoid upscale and crop issues
before:
after:
NOTE: the new image will accommodate a wide full width banner assuming that the artwork is setup that wide. I'd recommend designing with an art board using 3072 x 800 (double size for retina screens) with 1600px wide centered main area which will serve as the thumbnail on cards.
> fix: image positioning and use high-res for new blog entry

- .github/workflows/metrics.yml
- packages/api/db/tables.sql
- packages/api/scripts/cmds/db-types.js
- packages/api/src/routes/metrics.js
- packages/api/src/utils/db-client.js
- packages/api/src/utils/db-types.d.ts
- packages/cron/package.json
- packages/cron/src/bin/metrics.js
- packages/cron/src/jobs/metrics.js
- packages/cron/src/lib/utils.js
- packages/niftysave/package.json
- yarn.lock
* They should not be generated on-the-fly
* It restricts us to 30s per query (pgrest heroku dyno)
* Can cause us problems with prom agent reading them (it times out)
* ...needs to cache or expose to perf issues
* They should be calculated from the replica
* So they don't impact performance of the production DB
This PR:
* Stores the current value for each metric in the DB
* Adds a cron job for re-calculating metrics every 10 minutes
* Connects to the replica DB to calculate stats
* Writes to a new table `metric`
* Updates the `/metrics` endpoint to query the `metric` table for the latest value
> fix: metrics

- packages/api/src/routes/metrics.js
- packages/cron/package.json
...also adds the missing "start:metrics" script 🤦
> fix: value when metric is missing in db

- packages/api/src/routes/metaplex-upload.js
- packages/api/test/metaplex-upload.spec.js
- packages/api/test/scripts/fixtures.js
This updates the metaplex endpoint to require a `mintingAgent` tag (added in https://github.com/nftstorage/metaplex-auth/pull/22), and pulls the `agentVersion` tag out of the payload if it's present.
The metaplex-auth PR above also changes the name of the `solana-cluster` tag to `solanaCluster`, since I originally used kebab-case for some reason and now regret my life choices. So this PR updates the backend to read the new tag. I was thinking we could briefly support both, but since we don't have any real traffic here yet it seems alright to just make the breaking change, especially since requests made with the old version would fail anyway due to the missing `mintingAgent` tag.
> feat(api): add mintingAgent tag to metaplex token

- packages/cron/src/jobs/pins.js
Content from Cluster 1 has been moved to Cluster 3.
When cluster 2 has finished transferring we'll migrate the database, but this will get the pin cron job moving until then.
> fix: query cluster 3 for status

- README.md
Updates the README, adding badges that link to our discord channel and twitter account. Preview:
refs #1102
> feat: add discord and twitter badge

- packages/api/db/tables.sql
Crons for Pins and Metrics perform queries filtering out by columns of Pin and Upload table. We need to add indexes to these columns to boost performance.
TODO:
> perf: add indexes for pins and metrics cron improvements

- packages/gateway/src/durable-objects/generic-metrics.js
- packages/gateway/src/index.js
- packages/gateway/src/metrics.js
- packages/gateway/test/metrics.spec.js
- packages/gateway/test/utils.js
- packages/gateway/wrangler.toml
For metrics that are not related to a specific IPFS public gateway, we were only tracking the sum of response times for the winner requests. However, we also need to track the total number of requests so that we can have proper visualisation of https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations
> fix: gateway metrics track total winner successful requests

- packages/gateway/src/durable-objects/gateway-metrics.js
- packages/gateway/src/index.js
- packages/gateway/test/utils.js
- packages/gateway/wrangler.toml
This fixes histogram metrics, as they were being calculated in the opposite logic. We track metrics "le" https://ipfs-staging.nft.storage/metrics. For example, considering a response time of 1000ms, all the buckets bigger than 1000 should be incremented in order to track the counts of "less or equal" to the bucket and be able to properly compute metrics like 95th percentile.
More info:
- https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile
- https://www.robustperception.io/how-does-a-prometheus-histogram-work
> fix: gateway histogram metrics

- packages/api/db/tables.sql
The `meta` field is actually now used by both PSA and the `/metaplex/upload` endpoint.
> docs: update comment on meta field in upload table

- packages/website/components/blog/cards.js
- packages/website/components/tags.js
- packages/website/styles/blog.css
addresses problem with #1158 for mobile container as well as preventing titles from being cut off all together on any device.
> fix: update size and alignment of cards while allowing height to expand

- packages/gateway/src/metrics.js
For properly visualising in Grafana an Histogram Quantile we need an upper bound +inf with the total number of successful requests per https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile
> fix: gateway metrics for prometheus histogram requires upper bound +inf

- .github/workflows/cron-pins-failed.yml
🤦 I'm an idiot - forgot to update here.
refs https://github.com/nftstorage/nft.storage/pull/1172
> fix: add pg connection string to failed pins cron

- packages/gateway/src/gateway.js
We were not previously detecting in the winner request response if fetch response was successfully. This typically did not represent a problem because usually the errors would be timeouts. However, after trying a load test scenario in my local machine I noticed that `cf-ipfs.com` has rate limited enabled (don't know at this point what are the conditions of it, can't find documentation on this...).
So, when we hit the CF rate limit, every request was immediately responded with the Error, instead of waiting for further responses.
In this PR, I added a loop cycle where we wait until one request succeeds, properly tracking potential errors. A `GatewayResponsePromise` was created to track of the state of each promise and rely on `p-any` to wait for further results in a simple fashion.
As a …
> fix: properly track errors on winner gateway fetch

- packages/website/components/copyButton.js
- packages/website/pages/files.js
- packages/website/styles/table.css
Using flexbox we can have the width get inherited so that it fits as much as it can before truncating the cid.
also updates the popover to prevent it from getting cutoff
> Fix: issue 1152 cid truncation

- packages/gateway/src/metrics.js
- packages/gateway/test/metrics.spec.js
This PR fixes prometheus metrics naming per best practices and conventions defined in https://prometheus.io/docs/practices/naming/ . Thanks @alanshaw for the pointer ❤️ 
In summary, the changes are:
- A metric name should have a (single-word) application prefix relevant to the domain the metric belongs to => made it nftgateway instead of previous two words
- A metric name should use base units => milliseconds converted to seconds
- A metric name should have a suffix describing the unit, in plural form (or total for a unit-less accumulating count) => all "total" are now suffixes and unit applied where applicable (response time seconds)
Closes https://github.com/nftstorage/nft.storage/issues/1182
> fix: gateway prometheus metrics best practices naming

- packages/api/src/routes/metrics.js
- packages/cron/src/jobs/metrics.js
Partially closes https://github.com/nftstorage/nft.storage/issues/504
Note: This is not really unique content dag size as detailed in https://github.com/nftstorage/nft.storage/issues/504#issuecomment-1025890582
> feat: track content bytes total metric

- packages/client/package.json
- packages/client/src/lib.js
- yarn.lock
Given we use a CarReader now, we can only close the blockstore once pack is finished.
Also updated @web-std/fetch to avoid `Error: Cannot find module '/home/runner/work/nft.storage/nft.storage/node_modules/@web-std/fetch/dist/index.cjs'`
Closes https://github.com/nftstorage/nft.storage/issues/1186
> fix: client close blockstore on store directory and store blob

- packages/gateway/src/constants.js
- packages/gateway/src/gateway.js
Part of https://github.com/nftstorage/nft.storage/issues/1181 implemented. Only cache when content smaller than max object size limit https://developers.cloudflare.com/workers/platform/limits#cache-api-limits
Will track metrics in follow up PR
> fix: only cache when content length smaller than max object size

- packages/gateway/src/durable-objects/summary-metrics.js
- packages/gateway/src/gateway.js
- packages/gateway/src/index.js
- packages/gateway/src/metrics.js
- packages/gateway/test/metrics.spec.js
- packages/gateway/wrangler.toml
Adds content length histogram tracking, as well as content length of cached responses, so that we can compare the amount of data we had cached
Closes https://github.com/nftstorage/nft.storage/issues/1181
> feat: track content length histogram

- packages/gateway/src/gateway.js
This PR adds [`x-forwarded-for`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) IP from client to work around rate limiting from ipfs.io gateway. As part of support in https://github.com/protocol/bifrost-infra/issues/1609
The client IP is obtained from https://developers.cloudflare.com/workers/runtime-apis/headers#request-headers
I made this specific to the ipfs.io gateway to make clear that only it has support for this, but we could also just send it in all of them.
Tested by creating a route where response is just the headers of request in staging and confirmed it has my public IP.
> feat: gateway with x-forwarded-for ip for ipfs.io gateway

- packages/gateway/src/durable-objects/gateway-metrics.js
- packages/gateway/src/durable-objects/summary-metrics.js
- packages/gateway/src/index.js
- packages/gateway/wrangler.toml
Re adds durable objects per environment and also resets completely migrations. Because I created a migration locally and I ended up messing the migrations completely. The good part is that we needed a clean up
> fix: reset durable objects migrations

- packages/client/package.json
This is the nft.storage equivalent of  https://github.com/web3-storage/web3.storage/pull/930. It adds `./dist/bundle.esm.min.js` to the package exports to fix production builds that use the pre-bundled lib.
> fix: add pre-bundled esm build to package exports

- packages/website/lib/faqContent.js
- packages/website/pages/faq.js
clarify that the 31gib limit is per upload, and note the extra step required for http api users
> clarify file size/upload limits

- packages/website/pages/files.js
Fixes regression where NFT type uploads do not link to the `metadata.json` file on the gateway.
> fix: gateway link for nft type uploads

- packages/gateway/src/gateway.js
Fixes get headers function to use the `.get` function. While `['X-Forwarded-For']` was working, `['cf-connecting-ip']` was not working and it was resulting on  `undefined,...` https://github.com/protocol/bifrost-infra/issues/1609#issuecomment-1032018181
This fixes it, already tested
> fix: gateway get headers record

- packages/website/lib/faqContent.js
This updates the FAQ entry about rate limits with the correct per-token limit.
> fix(website): fix rate limit definition in FAQ

- packages/website/posts/2022-02-08-what-am-buying.mdx
Otherwise blog post appears in the middle of the list and is not "featured" at the top of the page.
In the futurem please check the preview link before merging so doesn't happen again.
> fix: blog post date

- packages/website/pages/files.js
> fix: line height for storage providers

- packages/gateway/src/durable-objects/gateway-metrics.js
- packages/gateway/src/durable-objects/summary-metrics.js
- packages/gateway/src/gateway.js
- packages/gateway/src/index.js
- packages/gateway/src/metrics.js
- packages/gateway/src/utils/histogram.js
- packages/gateway/test/metrics.spec.js
- packages/gateway/wrangler.toml
This PR adds:
- track cached response times
- histogram summary response times
> feat: track cached response times

- packages/gateway/src/durable-objects/gateway-rate-limits.js
Per previous load experiments and talks with Pinata team, let's change the rate limit prevention criterium
Cloudflare was in theory 100 req / minute, but I got cases where I got rate limited by 30 fast requests... I did a small test using 16 req / 10 seconds instead, and it seem way more stable.
Pinata does not rate limit dedicated gateways. This might change in the future, but as an enterprise customer they will reach out first and will try to get a solution together with us if it would start to be rate limited. Suggesting doubling what they offer on their public gateway and we can see later on if we can increase more
> fix: tweak rate limits per gateway

- packages/gateway/src/constants.js
- packages/gateway/src/durable-objects/gateway-redirect-counter.js
- packages/gateway/src/env.js
- packages/gateway/src/gateway.js
- packages/gateway/src/index.js
- packages/gateway/src/metrics.js
- packages/gateway/wrangler.toml
Adds a counter to track redirects when rate limited to have a metric and better view if all fail in any situation.
> feat: gateway track redirect counts

- packages/gateway/src/constants.js
- packages/gateway/src/gateway.js
Fixes two minor issues:
- get durable object URL
- when timeout we were not getting access to gateway URL nor properly handling abort error (code does not exist, at least in CF environment)
> fix: gateway get durable object request function

- packages/website/public/schema.yml
Adds a note about rate limits to the HTTP spec (copied from this similar [w3s PR](https://github.com/web3-storage/docs/pull/216)), but I'm not 100% sure it's accurate, since #877 suggests that we have global limits here instead of per-token limits.
> chore(website): add info about rate limits to http docs

- packages/gateway/README.md
Adds usage section to the readme, as well as rate limit information
Closes https://github.com/nftstorage/nft.storage/issues/1196
> docs: add gateway usage and rate limit information

- packages/gateway/src/durable-objects/gateway-rate-limits.js
- packages/gateway/src/gateway.js
- packages/gateway/src/index.js
- packages/gateway/wrangler.toml
> fix: not prevent ipfs io requests

- packages/website/pages/files.js
Fixes capitalization of "URL" in action menu.
> fix capitalization of URL

- packages/website/styles/nextra-overrides.css
Fixes callout overflow issue on mobile
> fix: callout overflow issue on /docs mobile

- packages/website/pages/docs/quickstart.md
Fixes the broken link for javascript client lib, inside of quickstart.
> Fixed broken link

- packages/website/pages/docs/quickstart.md
Revert, then new pr with correct format so it goes into website release as a fix
Reverts nftstorage/nft.storage#1339
> Revert "Fixed broken link"

- packages/website/pages/docs/quickstart.md
Fix broken link and get into website release with correct prefix.
> fix: broken link

- packages/api/db/tables.sql
* pinning allowlist and user account storage limits can be managed by this single table without the need for one-off tables e.g. pinning_authorization.
* this allows the admin.storage site to easily manage tags.
web3 pr [here](https://github.com/web3-storage/web3.storage/pull/955)
> Adding user_tag table to facilitate user restricted application features.

- packages/gateway/src/gateway.js
This PR increases gateway timeout to 60s (same as ipfs.io)
I was talking last night with @dchoi27 and we should increase the timeout as we might not have data in Peered Cluster nodes, and need to perform DHT lookups. This is particularly important for users that store their data in Pinning Services.
I was looking into `cf-ipfs` and `pinata` dedicated gateway timeouts and they are bigger than 60s. But I think 60s should be a reasonable timeout to have.
> fix: increase gateway timeout

- client-gen.sh
- packages/website/public/schema.yml
This fixes the path to the schema file in `client-gen.sh`, and copies the `responses` section in the schema from the `upload` operation to `store`, to get rid of these errors:
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
| Error count: 1, Warning count: 1
Errors: 
-attribute paths.'/store'(post).responses is missing
Warnings: 
-attribute paths.'/store'(post).responses is missing
```
closes #1370
> chore: fix client-gen script and openapi schema

- packages/client/package.json
- packages/client/typedoc.json
This sets the `gitRevision` typedoc option to `main` so that links to the source always target the main branch instead of the current git hash.
I also moved the typedoc options to a `typedoc.json` file, since they were getting kind of hard to maintain as cli args in the package.json script entry.
Closes #1299
> fix: link to main branch from generated client docs

- packages/api/package.json
- packages/gateway/src/env.js
- yarn.lock
Adds Cloudflare Durable object types inline and the `@cloudflare/workers-types` dev dependency. The Durable objects types are not exported from `@cloudflare/workers-types`
> fix: add durable object types

- packages/website/pages/files.js
Currently, in local development, window defocus / refocus causes /files to load again. This pr fixes that.
> fix: fixes local refetch issues on /files

- packages/website/lib/faqContent.js
- packages/website/pages/index.js
- packages/website/pages/terms.js
- Updates copy to clarify that size limit of 31 GiB applies to individual uploads.
Closes #1421
> chore: update upload size limit copy

- packages/website/styles/nextra-overrides.css
Removes the top offset in nextra fixed position. checked in Chrome, FF, Safari
> fix: nextra scolling inline style

- packages/website/pages/docs/how-to/meta.json
- packages/website/pages/docs/how-to/mint-solana.md
This adds a how-to about minting on Solana using the candy machine CLI. I tried to thread the needle of not duplicating the official docs too much, especially for the pre-req section where they'll do a better job keeping the required version numbers, etc up to date.
cc @Annamarie2019, who kindly offered to do a proof-reading pass (thanks again!)
also cc @jnthnvctr for situational awareness :)
Closes #1374
> feat(docs): add how-to for minting on solana with metaplex

- .github/workflows/cron-metrics.yml
- packages/cron/src/jobs/metrics.js
- packages/cron/src/lib/utils.js
1. Switches to using `pg.Pool` so multiple SQL commands can be run concurrently!
1. Adds some logging to the metrics cron job to make debugging easier.
1. Increase the timeout by 5 mins!
> fix: metrics cron

- packages/website/pages/docs/client/js.md
Closes #1517 
- Adds missing link
- updates format of links so that inline code not mixed with non-code, fixing space in middle of link and improved readability
> fix: client docs markdown fixes

- packages/website/pages/docs/how-to/store-directory.md
Updates the store directory example to strip the directory name out using the new `pathPrefix` option in `getFilesFromPath`.
Also adds a callout about using async iterator filesFromPath instead
of getFilesFromPath if you have a lot of files. 
If people ask, we should think about writing up an example for that also. I've been avoiding it so far since it's a little more complex & needs more explaining. But long-term it's probably helpful to head off questions from people trying to read everything into RAM and hitting limits.
> fix(docs): add pathPrefix to storeDirectory example

- packages/website/pages/faq.js
- packages/website/styles/faq.css
- packages/website/styles/global.css
Closes #1511 
```
Changes to FAQ page:
- Removes “Table of Contents” above the list of questions
- Increases the line height in the question list
- Decreases size of code snippets in question titles
```
> fix: update styles of faq page

- packages/website/styles/utils.css
Utils was updated to have more tailwind style CSS, but nextra expects hidden to be a display property.
> fix: visibility issue conflict with nextra themes

- packages/website/pages/docs/how-to/retrieve.md
- packages/website/styles/nextra-overrides.css
@Codigo-Fuentes looks like the package badges were removed. I also can't duplicate the callout overlap/z-index problem on latest so it may no longer be an issue. Tabs and other items fixed marked below.
Partially closes #1329
> fix: docs tabs breaking and other markdown issues

- .github/workflows/cron-metrics.yml
- packages/api/db/tables.sql
- packages/api/docker/postgres/00-initial-schema.sql
With https://github.com/nftstorage/nft.storage/pull/1400 in and new metrics being calculated, there were a few of new issues:
- `stats` user did not have access to cargo schema https://github.com/nftstorage/nft.storage/runs/5460080791?check_suite_focus=true#step:5:119
- timeout is not likely enough https://github.com/nftstorage/nft.storage/runs/5462071587?check_suite_focus=true#step:5:90
- sum content dag size is the clear bottleneck (should have an index like we have in web3s)
The queries taking longer are:
```
2022-03-08T09:36:15.852Z metrics:updateMetrics updateTotalUploadPast7 took: 827061ms
```
and `updateContentRootDagSizeSum` which is the long lasting one
Question: Should we consider `inserted_at` idx for upload considering the execution time of `updateTotalUploadPast7`?
> fix: metrics cron permissions and increase timeout

- packages/api/db/tables.sql
- packages/cron/src/jobs/metrics.js
- packages/cron/src/lib/utils.js
This PR:
- specifies max concurrent queries gathering metrics to avoid duration of some being influenced by others running in the PG pool
- adds `inserted_at` idx to upload to boost performance of metrics queries
> perf: metrics max concurrent queries and adds inserted at index to upload

- packages/website/components/navbar.js
- packages/website/lib/magic.js
- packages/website/pages/_app.js
Fixes #1556, removes localstorage and _always_ calls magic link to verify user is authenticated.
> Fix: remove localstorage, only use magic link api for auth status

- packages/gateway/src/durable-objects/gateway-rate-limits.js
- packages/gateway/src/index.js
- packages/gateway/wrangler.toml
This PR adds our dedicated CF gateway as the gateway to be used 🎉 
I had our dedicated CF gateway `cf.nftstorage.link` setup with Cloudflare team, this will be an offering from them in the future and we had a manual process with them to have the DNS setup and proxying to ipfs.cloudflare.com.
With this dedicated gateway we have more freedom and powers with custom rate limits. With this in mind, a set of rules were put in place to avoid abuse and hammering this domain:
- [Firewall rule](https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/nftstorage.link/firewall/firewall-rules) blocking all traffic matching `cf.nftstorage.link/*` from the outside world (only our worker can access it, same CF zone ID)
- [Rate limit rule](https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/nf …
> feat: gateway with dedicated cf gateway

- packages/website/styles/nextra-theme.css
> fix: add label to docs menu to prevent double hamburger ambiguity

- packages/website/lib/statsUtils.js
- packages/website/pages/stats.js
- packages/website/styles/stats.css
- fixes the safari 1px white border
- normalizes the bytes format function
- adds loading spinner while data is getting fetched
> fix: reapply stats format function and add loading

- packages/website/pages/stats.js
Upload stat was formatted as bytes, but it's a total count not a byte count, so MB should be M for millions.
> fix: upload stat isnt a byte count, but a number count

- .github/workflows/gateway.yml
So we changed Gateway zone id to be `nftstorage.link` in Cloudflare in https://github.com/nftstorage/nft.storage/pull/1546
This means we need a new API Token for it instead of using the nft.storage zone id token
Failed deploy at https://github.com/nftstorage/nft.storage/runs/5493727385?check_suite_focus=true#step:6:47
> fix: gateway release cf token

- packages/api/package.json
- packages/api/src/routes/pins-add.js
- packages/api/src/routes/pins-replace.js
- packages/api/src/utils/router.js
- packages/api/test/pin-add.spec.js
- packages/api/test/scripts/helpers.js
- yarn.lock
We need to pin by source CID to be consistent with all other uploads.
...also a fix to ensure the pin metadata is filtered correctly.
refs https://github.com/nftstorage/nft.storage/issues/1490
Part 2 is to pin all v0 source CIDs.
> fix: pin by source CID

- README.md
- packages/api/README.md
- packages/api/src/bindings.d.ts
- packages/api/src/utils/db-client.js
- packages/api/test/scripts/helpers.js
* see #1389 #1381
* Adding a missing comma.
* Filtering tags on deleted_at is null.
* Removing some PSA_ALLOW references.
> fix: Refactor pinning authorization logic to use user_tag table

- packages/website/pages/manage.js
Before and after:
now matches /files page
> feat: add actions menu for api keys page

- packages/website/package.json
- packages/website/pages/files.js
- yarn.lock
1. Fixes "View URL" to use the `nftstorage.link` gateway
* ...also to not use `ipfs://`
3. Fixes "Copy IPFS URL" to always be a `ipfs://<CID>` URL.
* Upgrades CID to v1 (if not already) since CID used in host part of URL must be case insensitive
resolves https://github.com/nftstorage/nft.storage/issues/1617
> fix: action menu URLs

- packages/website/posts/2022-01-20-decentralizing-nft-storage.mdx
@dchoi27 mdx automatically started the paragraph before the img so adding these without a line break was effectively nesting paragraphs which is not semantic.
> fix: blog formatting with mdx p tag

- packages/website/pages/login.js
GitHub capitalizes the H in their name
> fix: capitalize H in GitHub

- packages/website/pages/stats.js
> fix: swap stats image, img already exists in assets folder

- .github/workflows/website_cd.yml
- .github/workflows/website_pr.yml
Motivation: https://github.com/nftstorage/nft.storage/issues/1242
* Get rid of old 'website.yml' gh action that would run both on PRs to main and push to main
* Add website_pr.yml action
* runs tests on all PRs modifying website, not just those into main branch
* Add website_cd.yml (continuous delivery)
* runs tests - seems worth the time-cost to re-test before release
* runs release-please - my understanding is that this action creates a PR from main -> release branch (so it's fine to never run it on PRs)
> Replace 'website' action with website_pr and website_cd

- packages/website/lib/faqContent.js
- packages/website/pages/docs/troubleshooting.md
This adds an entry to the troubleshooting page about the "module not found" issues caused by bundlers that don't support the package.json `exports` map. 
It also updates the FAQ about webpack 4 to link to the troubleshooting page. I tried adding an example of the pre-bundled import to the FAQ page, but I couldn't figure out how to quote the statement so that `faqContent.js` didn't try to treat it as an actual import and complain that it couldn't find the package.
Closes #1561
> fix(docs): add pre-built bundle info to troubleshooting & update faq

- packages/gateway/wrangler.toml
When latest release happened, a new worker triggered was added again and response was being served from worker instead of page zone rule
Closes https://github.com/nftstorage/nft.storage/issues/1579
> chore: gateway toml config trigger remove outdated

- packages/website/pages/files.js
Per Deceptive site ahead error from google let's temporarily revert back gateway domain until we have it unblocked
> fix: website gateway url tmp revert

- packages/api/db/config.sql
- packages/api/db/functions.sql
- packages/api/db/reset.sql
- packages/api/db/tables.sql
- packages/api/docker/docker-compose.yml
- packages/api/docker/postgres/Dockerfile
- packages/api/src/utils/db-types.d.ts
- packages/api/test/nfts-upload.spec.js
Partial of #1126 (does not include partitioning).
Included in this PR:
- Improves the docker-compose for the database by specifying CPU and RAM constraints
- Updates the postgres dockerfile to use the latest PG (13) to match what we run in production/staging
- Also improves it by adding additional logging, which is useful when working with the DB on local dev
- Improve the DB configuration
- Many other settings aren't able to be configured like this (Heroku doesn't expose most flags), noted in #782 so I did what I could within the constraints of what we can do inside the DB
- Improves the "backup" system - instead of having its own table with a many to one relationship, add a new key `backup_urls` for each upload. This removes a redundant large table (12M uploads = > 12M backup rows), and …
> feat: db optimizations, backups optimizations

- packages/website/next.config.js
- packages/website/pages/docs/how-to/meta.json
- packages/website/pages/docs/how-to/ucan.md
This adds a new how-to doc for using UCAN, to close #1431.
There's a lot of copy/paste from the ucan.storage README, but I left out some of the more generic stuff like generating keypairs and just linked to the README docs for those. I figure that should be a bit less work if the ucan-storage API changes at all, and this how-to seems long enough without showing those examples. It does mean kicking the reader off to another page to get the complete picture though, so if anyone feels strongly about that we can copy that stuff over as well.
> feat(docs): add UCAN how-to

- packages/api/src/bindings.d.ts
- packages/api/src/index.js
- packages/api/src/routes/cors.js
- packages/api/src/routes/metaplex-upload.js
- packages/api/src/routes/nfts-upload.js
- packages/api/src/utils/db-client-types.ts
- packages/api/src/utils/db-client.js
- packages/api/src/utils/db-transforms.js
- packages/api/test/nfts-upload.spec.js
- packages/client/src/lib/interface.ts
- packages/website/lib/mock_files.js
- packages/website/pages/files.js
> feat: labeling uploads on files

- .github/workflows/conventional-commits.yml
Motivation:
* robot-enforcement of [policy](https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1648067416521459?thread_ts=1648065445.982479&cid=C02BZPRS9HP)
Changes
* Add a github action to enforce that PR titles follow conventional commits (so that squash merges of PRs dont lead to commit messages violating [this policy](https://github.com/nftstorage/nft.storage#how-should-i-write-my-commits))
> ci: add .github/workflows/conventional-commits.yml

- packages/api/src/index.js
- packages/api/src/routes/nfts-upload.js
- packages/api/src/utils/db-client-types.ts
- packages/api/src/utils/db-client.js
- packages/api/test/nfts-upload.spec.js
We had been using ID but id is not accurate, content_cid is the id that relates nft uploads to uploads.
> feat: content_cid not id is used from nft data upload not uploads

- packages/cron/src/jobs/pins.js
TLDR; we pin to cluster using `source_cid`, but the pins cron job checks status by `content_cid` so it is not found. For most data this is not a problem but when v0 CIDs are pinned their status never gets updated to `Pinned`.
This is a long standing bug that was masked by a regression that got fixed recently here: https://github.com/nftstorage/nft.storage/pull/1634
In Web3.Storage this query is harder so we actually downgrade `content_cid` to v0 when found to be unpinned everywhere and re-check with cluster: https://github.com/web3-storage/web3.storage/blob/3231807f24190de3e5be810ab25ed9567fda41cb/packages/cron/src/jobs/pins.js#L73-L75
Fixes https://github.com/nftstorage/nft.storage/issues/1745
> fix: use source_cid in pin cron job

- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/rate-limiter.spec.js
- packages/website/components/cloudflareImage.js
- packages/website/pages/api-docs.js
- packages/website/public/schema.yml
- yarn.lock
Adds a new optional `Service` property `rateLimiter`. A rate limiter function returns a promise that resolves when it is safe to send a request that does not exceed the rate limit.
The API is rate limited by auth token @ 30 request every 10 seconds.
Each **instance** of the `NFTStorage` class gets a **new rate limiter** because it does not really make sense to create multiple client instances with the same token/endpoint (although note that it is possible). In the static API the **global limiter** is used unless a rate limiter function is passed as an option.
This should be sufficient for the vast majority of users. For 99.9% of folks there is **no change** here, just faster uploads because they won't get blocked for 30s if hitting the rate limit.
**Power users:**
The API is rate limited …
> feat: add rate limiter

- packages/website/pages/files.js
This allows us to release the blog posts. API can then be deployed separately, and then the frontend (with this change reverted).
> fix: temporarily hide upload name column

- packages/client/package.json
- yarn.lock
This should remove the warning from the repo:
I checked the docs that get generated and it still works and they look fine...
> chore: update typedoc dep

- packages/api/db/config.sql
- packages/api/db/functions.sql
- Raises the database statement timeout to 3 minutes, this should accommodate the existing cron jobs that take ~30s to run
- Adds a localized 30s timeout to uploads
- A future improvement would be to isolate the cron jobs and postgrest users in the DB, and each user can have a statement_timeout config aligned with their actual expected times
> fix: lift pg statement_timeout

- .github/workflows/api.yml
Motivation:
* api workflow isn't working isn't using valid syntax because I tried to include a secrets check in 'if' without testing (SORRY)
* https://github.com/nftstorage/nft.storage/pull/1789#issuecomment-1092972415
* https://github.com/nftstorage/nft.storage/pull/1698#pullrequestreview-936618267
Known Issues
* this is worth landing alone, but the api workflow will fail on forks that dont have that secret set. This other #1791 tries to tackle that
> ci(api): fix syntax of api workflow

- .github/workflows/api.yml
- packages/api/docker/docker-compose.yml
- packages/api/package.json
- yarn.lock
The IPFS Cluster v1 release has much improved perf, and some breaking API changes.
In this PR we upgrade the ipfs-cluster client and local test environment to work with the v1 cluster API.
CI was [failing for the API](https://github.com/nftstorage/nft.storage/actions/runs/2115915629), so this PR includes a change to that workflow to fix that.
After merging this PR 
- Update staging env cloudflare worker secrets for CLUSTER_SERVICE to IpfsCluster & CLUSTER_BASIC_AUTH_TOKEN from 1pass - to use the new staging cluster running ipfs-cluster@1.0.0-rc.4
- open a follow PR to update the cron package dep on ipfs-cluster client.
see: https://github.com/nftstorage/nft.storage/issues/1736
see: https://github.com/nftstorage/ipfs-cluster/releases/tag/v5.0.0
License: (Apache-2.0 AND MIT)
Signed-off-by: …
> feat: api support for ipfs-cluster@1.0

- packages/website/pages/docs/concepts/car-files.md
Fixes #1571 
This PR removes a hanging quote in the the CAR files docs page.
> fix: remove hanging quote in title

- packages/cron/package.json
- yarn.lock
Follow up of https://github.com/nftstorage/nft.storage/pull/1789 for today's migration. Should only be merged after api release #1749
> feat: cron update for cluster@1.0

- packages/cron/package.json
- packages/cron/src/bin/pins-failed.js
- packages/cron/src/bin/pins.js
- packages/cron/src/lib/fetch.js
- packages/cron/src/lib/ipfs.js
- yarn.lock
`node-fetch` does not support `getReader` (or at least the version we were using does not):
```
TypeError: stream.getReader is not a function
at ndjsonParse (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:627:25)
at ndjsonParse.next (<anonymous>)
at streamRequest (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:332:10)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async statusAll (file:///home/runner/work/nft.storage/nft.storage/node_modules/@nftstorage/ipfs-cluster/src/index.js:202:20)
at async file:///home/runner/work/nft.storage/nft.storage/packages/cron/src/jobs/pins.js:185:24
at async mapAndQueue …
```
> fix: pins cron

- packages/website/pages/new-file.js
Fixes #1514
This PR updates links to the JS Client Library and the NFT Storage docs Raw HTTP Requests pages from the `/new-file` page. (page seen when one clicks "Upload" from the Files page)
> feat: update links to JS lib and api docs

- packages/website/next.config.js
I realized just now that `yarn run build` in the website package always tries to upload to sentry, which doesn't work with the default local development `env.tpl` file we added in #1724.
The template sets `SENTRY_UPLOAD` to `false`, but that only affects our cli scripts. The current `next.config.js` always enables the sentry plugin if `env !== 'dev'`, so if you try to build locally you get:
```
npx next build
info  - Loaded env from /home/yusef/work/repos/nft.storage/packages/website/.env.local
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.
Sentry CLI Plugin: Command failed: /home/yusef/work/repos/nft.storage/node_modules/@sentry/cli/sentry-cli releases new website@1.44.0-undefined+1a29aa9
error: API request failed
caused by: …
```
> fix: enable next.js sentry plugin only if SENTRY_UPLOAD is true

- .github/workflows/api.yml
- .github/workflows/client.yml
- .github/workflows/website.yml
We already had a couple of occurrences when one package changing dependencies impacted other packages as their CI jobs did not run (api CI is currently failing due to https://github.com/nftstorage/nft.storage/pull/1701 changes from website deps).
When `yarn.lock` is changed, we should run all packages to avoid this
Needs fix from https://github.com/nftstorage/nft.storage/pull/1840
> chore: trigger package tests when yarn lock changes

- packages/api/src/index.js
This was added for local testing but never removed.
> fix: remove cluster API URL from /version endpoint

- packages/website/components/trustedByLogos.js
Fixes #1686
This PR updates the count from 20,000 to 30,000 logo users and adds a link to the github discussion page where users may upload their own logo to be used on the site.
> feat: update logo text and link to github

- packages/api/db/cargo.testing.sql
- packages/api/src/utils/db-client.js
In `.range(from, to)`, the `to` value is _inclusive_. The tests were not throwing because only one row in the fixture but in staging this breaks.
Fixtures updated to ensure multiple values are present in the DB.
> fix: single() on multiple rows

- packages/api/src/routes/nfts-upload.js
Bitswap spec is being updated to clarify the 2MiB limit: https://github.com/ipfs/specs/pull/269
go-ipfs chunker accepts a max size of 1MiB but protobuf wrapping can make it a bit bigger. Switching to 2MiB allows us to support blocks created using that max chunker size.
refs https://github.com/web3-storage/web3.storage/pull/1269
> fix: bump MAX_BLOCK_SIZE to 2MiB limit imposed by bitswap

- packages/api/src/errors.js
- packages/api/src/routes/nfts-upload.js
- packages/api/test/nfts-upload.spec.js
For sha256 hashed data we check the data in each block matches the multihash provided, to detect malformed uploads early and alert the user.
We may support other hash functions later.
A port of https://github.com/web3-storage/web3.storage/pull/1069
TODO:
License: (Apache-2.0 AND MIT)
> fix: verify CIDs match data in CAR uploads

- packages/website/pages/files.js
- packages/website/pages/manage.js
- packages/website/pages/new-file.js
- packages/website/pages/new-key.js
Fixes #1726
This PR updates several static props causing redirect issues on SSR / Hard Refresh. 
- Files page no longer redirects to home page on hard-refresh
- API Keys (/manage) no longer redirects to home pages on hard-refresh
- New File an New API Keys pages, on refresh, now redirect to their respective parent pages Files and API Keys
> fix: redirect to home page from files on refresh

- packages/website/.env.development
- packages/website/components/layout.js
- packages/website/lib/statuspage-api.js
Fixes #1728
This PR adds incidents notices to the NFT.storage banner. If there is an incident, it will take precedence over maintenance notices.
> fix: add incidents to banner

- packages/api/src/routes/nfts-upload.js
- packages/api/test/nfts-upload.spec.js
[We require a `Content-Type` to be set for each part of the multipart request.](https://nft.storage/api-docs/#operations-NFT_Storage-upload)
If users don't set this value `FormData#getAll()` returns a `string` not a `File`.
This PR prevents Sentry errors for invalid multipart (by our standards).
> fix: invalid multipart data error

- packages/api/src/errors.js
- packages/api/src/utils/auth.js
- packages/api/src/utils/db-client-types.ts
- packages/api/src/utils/db-client.js
- packages/api/test/db-client.spec.js
When an API key is blocked in admin.storage, it sets deleted_at to the current time, and then sets the last auth_key_history item to have status 'Blocked.'  This PR just updates the code to look at the status so it can send a unique error to the client when an API key is deleted via a block.
Closes #1382
> feat: return unique error message when using a blocked key

- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/lib.spec.js
- yarn.lock
Motivation:
* https://github.com/nftstorage/nft.storage/issues/1525#issuecomment-1129357723
* this allows end-users to defer buffering of large sets of files (e.g. large dirs), and just pass us an `AsyncIterable<File>`. If I'm reading the `packCar` code right, I think even we avoid buffering the whole file list in an array (though Blockstore may still do the equivalent)
> feat: storeDirectory accepts files as AsyncIterable<File>

- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/lib.spec.js
Motivation:
* https://github.com/nftstorage/nft.storage/pull/1921#discussion_r876243994
* this makes it so storeDirectory can accept POJO, not just dom File objects, which can make our docs code snippets even simpler when using `files-from-path`
> feat: storeDirectory accepts iter of file objects

- PEERS
Also removes old unused cluster peers (data has been copied to the 3rd cluster).
> docs: update cluster peers

- packages/api/src/utils/s3-backup-client.js
add `x-amz-checksum-sha256` header on s3 object put requests.
This is nice as we reuse our existing sha256 hash of the car as an integrity check. AWS will calculate the sha256 of the body it receives and send us a 400 BadDigest error if they dont match, to avoid storing CARs that had bits flipped in transit.
see: https://github.com/web3-storage/web3.storage/pull/1068
License: (Apache-2.0 AND MIT)
> fix: send checksum on s3 upload

- packages/website/pages/docs/how-to/store-directory.md
Depends on
Motivation
* make the documented way of doing this not buffer big dirs in a way that could crash https://github.com/nftstorage/nft.storage/issues/1525
> docs: Update docs/how-to/store-directory to pass files as AsyncIterable<File>

- packages/api/db/migrations/003-add-HasDeleteRestriction-type.sql
- packages/api/db/tables.sql
- packages/api/src/bindings.d.ts
- packages/api/src/errors.js
- packages/api/src/index.js
- packages/api/src/middleware/auth.js
- packages/api/src/routes/user-tags.js
* Adding the type and failing HTTP DELETE operations if this tag is set.
* See nftstorage/admin.storage#66
> feat: Adding HasDeleteRestriction user_tag

- packages/api/db/migrations/003-user_tag_proposals.sql
- packages/api/db/tables.sql
web3 PR [here](https://github.com/web3-storage/web3.storage/pull/1006)
* Users create records in this table and admins manage it.
> feat: DB schema and API for user_tag_proposal. (#1410)

- packages/api/src/utils/db-client.js
Fixes: #1877
This commit optimizes the metrics query to be less brittle
in the case that the dimensions array data changes or
takes on new values. Here, we query the presence
of the keys instead of the exact match of the
stringified array.
> feat: optimize metrics query

- examples/client/browser/README.md
- examples/client/browser/storeFromUrl.html
Adds an example showing how to store ERC-721 compatible metadata with image data retrieved from a URL on the internet.
Adapted from https://github.com/nftstorage/nft.storage/blob/main/examples/client/browser/store.html
> docs: add store from URL example

- packages/website/pages/docs/how-to/mint-custom-metadata.md
fixes #1886
This PR updates broken links from `../` to `/docs/` appearing to work locally but not on the Cloudeflare env.
> fix: update paths to start from root

- packages/website/styles/tooltip.css
fixes #1976
This PR adds an underline style to tooltip hyperlinks that would otherwise look like plain text. The color remains #000 to stay consistent with the current style guide.
> fix: add underline style to tooltip hyperlinks

- .github/workflows/cron.yml
- packages/cron/package.json
- packages/cron/src/bin/nft-ttr.spec.js
Motivation
* in review of #1945 , @alanshaw encoruaged me to remove this test. But when I tried, it led to an error when running the tests in github action. That appears due to combination of https://sharp.pixelplumbing.com/install#worker-threads and ava's default test isolation strategy which is to use worker threads. I tried configuring ava `require` opt to require sharp, but that didn't work. So let's just disable worker threads in ava in favor of using separate processes.
* an alternative solution would be to not use sharp since it has this worker thread quirk
> test: rm test of bin/nft-ttr cli func

- .github/workflows/cron-nft-ttr.yml
- packages/cron/src/bin/nft-ttr.js
- packages/cron/src/bin/nft-ttr.spec.js
- packages/cron/src/jobs/measureNftTimeToRetrievability.js
- packages/cron/src/jobs/measureNftTimeToRetrievability.spec.js
- packages/cron/src/lib/http.js
Motivation
* add logging to nft-ttr job to easily see what the request url and response status code of the pushgateway request is (e.g. in case the current setup does not lead to 200 ok)
* this instance label consistent with other uses of prom/pushgateway and helps at query time later
* @alanshaw encouraged me to
* also adds a test ensuring that a mocked pushgateway receives an http request as expected
> feat(cron): send instance=github_action label with retrieval_duration_seconds metric

- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/lib.spec.js
Adds `signal` (an [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)) as an optional parameter to methods that call the API.
resolves #1973
> feat: abortable API method calls

- packages/client/README.md
- packages/website/pages/docs/client/js.md
- packages/website/pages/docs/concepts/architecture-considerations.md
The `NFTStorage` class page is where folks need to be directed to.
Also adds a menu item to the reference docs.
> fix: link to NFTStorage constructor in API reference docs

- packages/client/src/platform.ts
I believe this fixes #1810.
I am not sure I know what exactly is happening in the TS, but I suspect issue is related to the fact that TS defines `File` in multiple places once as interface and another time overloading `File` as a class that implements that interface. It looks like `@tsconfig/node16` config causes `File` binding to be exported as opposed to both definitions.
Fix here explicitly overloads `FileExport` the same way and then exports it as `File` which seems to force TS to recognize binding as both interface and a binding.
P.S: I attempted to create simple test case to verify this but unfortunately failed to do so as it requires setting up another package with different tsconfig and which then needs to somehow reference `nft.storage` in the tree. All in all I don't think it's …
> fix: file import in some ts configurations

- packages/client/package.json
- yarn.lock
Added in https://github.com/nftstorage/nft.storage/commit/27394f6435ebfbead8cad609b2e92be4b69b4661 but not added to dependencies.
v2 does not have a default export and causes issues like https://github.com/nftstorage/nft.storage/issues/2069 when used by folks using that version in their projects.
v1.1.0 is currently the version used by `ipfs-car`.
resolves https://github.com/nftstorage/nft.storage/issues/2069
> fix: add missing dep it-pipe

- packages/api/package.json
- packages/api/src/errors.js
- packages/api/src/index.js
- packages/api/src/utils/auth.js
- packages/api/test/nfts-upload.spec.js
- packages/website/pages/docs/how-to/ucan.md
- packages/website/public/schema.yml
- yarn.lock
fixes https://github.com/nftstorage/nft.storage/issues/2092 
As per discussion today this changes ucan authorized request route to `/ucan-upload` and requires `x-agent-did` header to apply apply rate limiting.
> feat!: rate limiting by ucan agent did

- .github/workflows/website.yml
This PR fixes website workflow build. Automatic build is now disabled in CF, and as a result we need the ENV variables to be specified in the build here instead of tied with CF Dashboard
> fix: website workflow release build

- packages/api/src/utils/db-client.js
We sometimes see request failures for calls to FDW. In this case we actually get sent back non-JSON data and our postgrest client fails to parse it and throws i.e. does not _return_ an error.
We're seeing this in the upload flow because we immediately request our upload after it has been created. Our database is not under load, but the FDW database seems to sometimes not be available.
This PR handles the case when the call to FDW fails with a thrown error _not_ a returned one.
499 is [H27 - Client Request Interrupted](https://devcenter.heroku.com/articles/error-codes#h27-client-request-interrupted):
Here is the error our client throws because it receives HTML:
.
> fix: fdw fault tolerance

- packages/api/src/utils/s3-uploader.js
- yarn.lock
We're seeing more and more of the following errors. My suspicion is that the S3 client is not (or no longer) returning an error with `name: 'BadDigest'`. This PR changes the behaviour here to just always retry a failed upload once and adds the thrown error as the `cause` of a new `Error` so that we can retain context here (since the stack in sentry is not helpful).
> fix: always retry s3 upload

- packages/api/src/utils/db-client.js
`.single()` throws if no results are returned, but it is likely to not return any rows if the token has not been blocked.
> fix: check for token blocked

- packages/website/lib/constants.js
- packages/website/lib/magic.js
- packages/website/pages/_app.js
- packages/website/pages/callback/[[...redirectPath]].js
- packages/website/pages/login.js
If a user deep links to an authenticated route, these changes will navigate the user to the login page and after they log in they'll be redirected to their intended destination.
> fix: block navigation to authenticated routes

- packages/website/components/link.js
fixes #2133 
This PR adds the href to the nested `<a>` element of the link element. While this will be replaced during client-side routing, it will be used when opening in new window or new tab.
> fix: add href to child a element

- .github/workflows/cron-nft-ttr.yml
Motivation:
* I want to have more frequent metrics in grafana dashboard
* I want to verify that changing this is all that's required to increase metric frequency (it's possible the constraint is actually based on how often prometheus scrapes the pushgateway)
> feat: cron runs nft-ttr twice as often (every 15min)

- packages/api/src/utils/db-client.js
- packages/api/test/db-client.spec.js
- packages/website/pages/manage.js
closes https://github.com/nftstorage/nft.storage/issues/2138
This includes 3 fixes each of which should fix the issue
1. Enable the fix the popup menus so they're distinct
2. Add a unique constraint to the database to prevent duplicates (this might be a bad idea if there are duplicates already in PROD)
3. Added logic to check if a duplicate already exists and message that in the API layer
> fix: duplicate key name

- packages/website/pages/docs/concepts/car-files.md
is this the best link for the broken link in the page?
> fix: broken docs link

- packages/website/public/schema.yml
https://github.com/nftstorage/nft.storage/pull/2097 failed to remove this route from the schema (and consequently the API docs).
resolves https://github.com/nftstorage/nft.storage/issues/2155
> fix: remove ucan-upload route from schema

- packages/website/public/_redirects
This PR adds a redirect for nft.storage/blog to the new blog.nft.storage site.
> feat: redirect slash blog

- packages/api/package.json
- packages/api/test/nfts-store.spec.js
- packages/api/test/nfts-upload.spec.js
- yarn.lock
This closes #2088 by re-enabling the test we were skipping, now that miniflare preserves the full file path.
It also works around a bug I found while updating. Miniflare v2.7+ fails when you provide an instance of `FormData` from `@web-std/form-data` as the body of a `dispatchFetch` call. It also seems to fail when using the `FormData` built into node 18+. It likes `undici`'s `FormData` though :smile: 
Miniflare updated their `undici` dependency in the 2.7 release, so that seems likely to be the cause of the issue. It manifests as the body being sent with a content-type of `text/plain;charset=utf-8` instead of `multipart/form-data`, so the api route handler doesn't know what to do with it.
In `nfts-upload.spec.js` we were constructing a `FormData` directly, so the fix is just to import …
> chore: re-enable skipped test & workaround miniflare formdata issue

- packages/website/public/schema.yml
This adds a note to the HTTP API docs about `/store` being slower than `/upload`, since we had a few people surprised at the `/store` perf earlier.
> chore: add note about /store endpoint perf & recommend /upload

- packages/website/pages/docs/concepts/gateways.md
I would to be 30 seconds (I think 🤔 ) but now CF Firewall does not allow blocking duration smaller than the interval using to track rate limit. In other words, if we say 200req/min we need to block in same time unit (i.e 60 seconds).
There were some thoughts on doing some changes to accomodate this, like 100req/30s but we might hit other issues and need to think about this more carefully - read more at https://github.com/nftstorage/nft.storage/issues/2202#issuecomment-1273543142
Closes https://github.com/nftstorage/nft.storage/issues/2202
> fix: docs with incorrect blocking duration due to rate limits

- packages/api/src/utils/auth.js
- packages/api/src/utils/logs.js
Motivation:
* this way `Logging#setUser` can accomodate user ids that correspond to bigints
* avoid this mistake https://github.com/web3-storage/web3.storage/issues/2040
Related
* I noticed that the db-types user definition has `id: number`. I wonder if it should change to `bigint` or `text` (and underlying queries will need to change). https://github.com/nftstorage/nft.storage/blob/6fcd38923506965012505473b57afde2ce22973e/packages/api/src/utils/db-types.d.ts#L1188
* nft.storage prod counter isn't at risk of bumping into this soon, but it is a bigint underneath so it could happen.
> chore: api Logging#setUser expects user.id as string instead of number

- packages/client/package.json
tiny fix here: while your ESModule build is working totally fine, when downstream consumers are set up to use `nodenext` for their `module` & `moduleResolution` settings, typescript reads your `package.json` and sees that the `exports.node` points to the `src` folder and tries to also look there for the typescript typings
as per [the typescript docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) this just lets typescript know to still keep looking in the `dist/src` folder for the types :)
> fix: fix typescript nodenext resolution

- packages/api/src/utils/uploader/r2-uploader.js
Include the R2 key in the error message for better visibility when debugging.
We're getting rate limits for put with the same key...
> fix: include key in error message

- packages/client/src/lib.js
- packages/client/test/lib.spec.js
Per talk async with @alanshaw , setting default chunk size to 50MB to save us 5x in number of indexes needed to write/read R2
> fix: set client default chunk size to 50MB

- packages/api/src/routes/pins-add.js
- packages/api/src/utils/db-transforms.js
allows undialable nodes to connect to us when pinning via the pinning service api
see: https://github.com/web3-storage/web3.storage/pull/2255
see: https://github.com/web3-storage/pickup/pull/134
License: MIT
> feat: send `delegates` on pin add response

- packages/website/theme.config.js
Previously it'd just display "NFT.Storage Docs" in the title tag on every docs page.  Now it'll update to match the h1 on the page:
partially fixes #2304 .  To get dynamic og tags it looks like we might have to upgrade nextra (which means also upgrading React and nextjs).
> fix: use dynamic title in head on docs pages

- packages/api/src/utils/auth.js
This fixes the (currently) confusing and surprisingly common case when a user deletes their API token and then receives the error "user not found" when trying to use the deleted key to upload. The error confusingly says their user is not found...when actually it should say token not found.
I believe this change captures the intention of the original code - that is, if the token is deleted but not blocked, then respond with a "token not found" error.
> fix: deleted token error message

- packages/api/src/bindings.d.ts
- packages/api/src/routes/nfts-upload.js
- packages/api/src/utils/uploader/r2-uploader.js
- packages/api/src/utils/uploader/s3-uploader.js
there are a few entries in DUDEWHERE bucket with CIDv0. Example: https://dash.cloudflare.com/fffa4b4363a7e5250af8357087263b3a/r2/default/buckets/dudewhere-prod-0
This won't work with reading from freeway from w3s.link when we always redirect to CIDv1
> fix: dudewhere root cid should be content cid

- packages/client/src/lib.js
- packages/client/src/lib/interface.ts
- packages/client/test/lib.spec.js
Since we upped the default chunk size, folks uploading directories with thousands of small files are sometimes finding the worker exceeds resource limits 🤦‍♂️. This allows them to `encodeDirectory` and then `storeCar` with a smaller chunk size to allow the directory to upload successfully.
e.g.
```js
import { NFTStorage } from 'nft.storage'
import { filesFromPaths } from 'files-from-path'
const token = 'API_KEY' // your API key from https://nft.storage/manage
async function main() {
const storage = new NFTStorage({ token })
const files = await filesFromPaths(['/path/to/files'])
const { cid, car } = await NFTStorage.encodeDirectory(files)
console.log(`File CID: ${cid}`)
console.log('Sending file...')
await storage.storeCar(car, {
maxChunkSize: 1024 * 1024 * 10, // 10MB
onStoredChunk: …
```
> feat: custom chunk size

- examples/client/node.js/encodeDirectory.js
We have one for `encodeBlob`...not `encodeDirectory`...until now!
> docs: add encodeDirectory example

- .github/workflows/client.yml
- packages/api/package.json
- packages/client/package.json
- packages/client/src/lib.js
- packages/client/src/token.js
- packages/client/test/lib.spec.js
- packages/client/test/mock-server.js
- yarn.lock
Port of https://github.com/web3-storage/web3.storage/pull/2292
> fix: this param for fetch calls

- packages/website/package.json
- packages/website/pages/files.js
- yarn.lock
I've been trying to get the file list in the my development version working, and was struggling even after pointing the website at the production version.
It turns out that when this website was updated from Tachyons to Tailwind, a stray `collapse` style was left on the file list table:
https://github.com/nftstorage/nft.storage/commit/1a29aa96597f2d92014a7e2af560af7ceead5f08#diff-f8b81b815feea0a351b1a42218602943bda2f0d4cd44b009dbbbb5f7c8c35ddaR462
At the time this was fine! Tailwind didn't have a `collapse` style until version 3.2 and 3.0/3.1 were current at the time of the transition. The production site uses Tailwind 3.1 and works just fine.
However! The version specification for the `tailwind` package in the `website` project's package.json uses a "compatible with version" specifier …
> fix: pin tailwind to version used in production

- packages/api/package.json
- yarn.lock
we've hit a problem where the CBOR-decoding part of parsing the w3up delegation seems to be erroring and falling back to the JWT codepath here:
https://github.com/ipld/js-dag-ucan/blob/21bae4e0ad7ff76e0c7b73938dcc228726854a43/src/lib.js#L52
it's hard to tell exactly what's going wrong since this seems to work locally, so this is a shot in the dark - upgrading `@ipld/dag-cbor` should be harmless and may fix the problem we're seeing
> fix: upgrade @ipld/dag-cbor

- packages/api/src/utils/context.js
current theory is that this variable isn't what we expect - logging so we can debug in staging
> fix: log proof for debugging

- packages/api/wrangler.toml
We were running into an issue parsing the w3up UCAN.
It turns out that we rely on the platform's URL class to parse DIDs in @iplad/dag-ucan: https://github.com/ipld/js-dag-ucan/blob/21bae4e0ad7ff76e0c7b73938dcc228726854a43/src/schema.js#L136 that's a little quirky since DIDs are really URIs not URLs but it works! except....
Cloudflare's URL implementation is not spec compliant! https://developers.cloudflare.com/workers/runtime-apis/web-standards/#url-api
Critically, it only supports "URLs conforming to HTTP and HTTPS schemes" which, of course, DIDs do not.
So what was happening was this attempt to parse the UCAN was trying to parse as CBOR, failing and swallowing the error, and then falling back to JWT, which also failed, but it swallowed the original error: …
> fix: enable `url_standard` compatbility flag

- packages/api/src/routes/nfts-upload.js
… and instead wraps the stat.carBytes Uint8Array as a BlobLike
Context
* trying to make changes that help these code paths avoid the 'out of memory' others saw when testing on staging
Motivation:
* removing this `new Blob` could get rid of a memory allocation that could be contributing to 'out of memory'
* I think by passing a BlobLike to `uploadCAR` here and not a whole blob, there will not be downstream copies of the underlying bytes because this car BlobLike, once passed to `uploadCAR` will get passed to a `CAR.BlockStream` that streams out blocks without re-buffering the whole car bytes in memory https://github.com/web3-storage/w3up/blob/main/packages/upload-client/src/index.js#L107
> feat: uploadCarWithStat avoids copying stat.carBytes via Blob construction

- packages/api/src/index.js
- packages/api/src/repl.js
I was thinking to try something along these lines
> chore: expose simple route to debug

- packages/api/src/repl.js
This updates `/repl` endpoint to simply upload CARs so we can test it's limits, if works out we can rewire primary endpoint.
> chore: simple test case to check limits

- packages/api/src/repl.js
- packages/api/src/routes/metaplex-upload.js
- packages/api/src/routes/nfts-store.js
- packages/api/src/routes/nfts-upload.js
- packages/api/test/nfts-upload.spec.js
Attempt to remove need for car repacking
> fix: avoid car repack

- packages/api/README.md
- packages/api/package.json
- packages/api/scripts/cli.js
- packages/api/scripts/cmds/w3up-console-ucan-request.js
- yarn.lock
Context
* nft storage can now upload things to w3up spaces using w3up-client
* i wanted to be able to visualize the things that were being added now that we have that running a bit on staging.nft.storage
* console.web3.storage is good for visualizing w3up spaces
* but it isn't trivial to authorize a console.web3.storage session to be able to access the space, so I wanted to figure it out and document it for others
What?
* this adds a command to the nft.storage api cli script that prompts the user for some stuff that is in our configuration secrets vault, asks for a DID of their console.web3.storage session, then builds a UCAN delegation authorizing their console.web3.storage session to access the space and saves it as a CAR file. The UCAN CAR file can then be imported at …
> feat: added script to generate ucan for w3up space and docs for how to access the space using console.web3.storage

- packages/website/lib/constants.js
Allows folks to login to the old NFT.Storage.
> fix: use correct API URL for classic.nft.storage

- packages/api/src/routes/nfts-upload.js
- packages/api/test/nfts-upload.spec.js
commenting code out here because I'll make a cleanup pass to remove the switch entirely once this is stable in production
> feat: lock w3up uploads feature switch open

- packages/api/src/errors.js
- packages/api/src/utils/auth.js
- packages/website/components/deprecationBanner.js
- packages/website/components/footer.js
- packages/website/components/layout.js
- packages/website/pages/files.js
- packages/website/pages/privacy.js
- packages/website/pages/terms.js
Make all (most?) of the requested changes from https://github.com/orgs/w3s-project/projects/1/views/1?pane=issue&itemId=57594940
Note that once this PR is deployed, new user signups will be disabled - I did not put these behind a feature flag as there doesn't seem to be a strong need for one.
A few caveats:
1) I put the same banner at the top of every page - since the menu is in the global layout it's tricky to get different banners displaying on different pages. This means that the requests to have different pages link to different URLs are challenging to accommodate, so I've gone down the easy path.
2) The error message for new users is a little janky - I followed the letter of the request but it's not terribly pretty:
We could make this prettier but it's nontrivial work, so I'm …
> feat: NFT.storage changes

- packages/api/package.json
- packages/api/src/bindings.d.ts
- packages/api/src/routes/nfts-get.js
- packages/api/src/routes/nfts-upload.js
- packages/api/src/utils/context.js
- packages/api/src/utils/db-client.js
- packages/api/src/utils/w3up.js
- packages/api/test/nfts-get.spec.js
- packages/api/test/utils/w3up-testing.js
- packages/website/lib/api.js
- packages/website/pages/files.js
- yarn.lock
Fetch deal information from w3up.
There's no way to "multi-get" deal info for more than one upload so I've reworked the deal info in the files list - if it has deals from dagcargo it will just use those, and if it doesn't, it will display a "load deals" button:
When clicked, it will find the shards of the upload and find filecoin info for each of them. If it doesn't find any filecoin info in w3up it will display the "queuing" status and tooltip as it did in the past:
This required updating the "get NFT" API endpoint to look for filecoin info from w3up.
> feat: show deal info from w3up

- packages/api/src/routes/nfts-list.js
- packages/api/src/routes/pins-list.js
- packages/api/src/utils/db-client.js
- packages/api/src/utils/json-response.js
- packages/api/test/nfts-list.spec.js
You can't display a progress bar if you don't know what you're progressing toward :)
Essentially, use the count feature for posgrest-js that is used in web3.storage old
- add to count db.listUploads feature, which changes return type
- modify JSONResponse to actually allow passing headers
- update tests, though I wasn't able to run them cause mysterious connection refusal errors with my docker setup. but I think I got them passing here
> feat(api): add count to list nfts api
