nftstorage/nft.storage

- README.md
- client/Readme.md
- client/src/api.d.ts
- client/src/lib.js
- package.json
- site/package.json
- site/src/bindings.d.ts
- site/src/constants.js
- site/src/errors.js
- site/src/index.js
- site/src/models/nfts.js
- site/src/models/users.js
- site/src/pinata.js
- site/src/routes/auth.js
- site/src/routes/cors.js
- site/src/routes/delete.js
- site/src/routes/homepage.js
- site/src/routes/logout.js
- site/src/routes/status.js
- site/src/routes/upload.js
- site/src/utils/auth0.js
- site/src/utils/jwt.js
- site/src/utils/multipart/search.js
- site/src/utils/redirect.js
- site/src/utils/utils.js
- site/wrangler.toml
- wires file upload endpoint with pinata
- added status api endpoint
- added delete api endpoint
> Implement backend endpoints

- client/src/lib.js
This will not be at `api.` for ease...
> fix: endpoint URL

- .github/workflows/client.yml
- client/README.md
- client/package.json
- client/src/lib.js
- client/src/lib/interface.ts
- package.json
> feat: client docs

- client/src/lib.js
> fix: error property is an object with a message

- package.json
- site/package.json
- site/src/bindings.d.ts
- site/src/routes/nfts-upload.js
- website/package.json
- website/public/schema.yml
> feat: add deals types and schemas, remove links

- site/src/index.js
- site/src/utils/router.js
> fix: fix cors when auth fails

- .github/workflows/client.yml
- .gitignore
- client/README.md
- client/package.json
- client/test/lib.spec.js
- client/test/service.js
> feat: 100% test coverage

- README.md
- site/package.json
- site/src/bindings.d.ts
- site/src/cluster.js
- site/src/constants.js
- site/src/pinata-psa.js
- site/src/routes/nfts-upload.js
- site/src/routes/pins-add.js
- site/src/routes/pins-delete.js
- site/src/routes/pins-get.js
- site/src/routes/pins-list.js
- site/src/routes/pins-replace.js
- site/wrangler.toml
TODO:
* Get DAG size from IPFS proxy (will send separate PR)
> feat: persist to IPFS Cluster

- client/src/lib.js
- client/src/lib/interface.ts
- client/test/lib.spec.js
- client/test/service.js
- client/test/test.js
- site/src/bindings.d.ts
> fix: update deal types to reflect actual structure

- site/src/jobs/pins.js
- site/src/models/nfts.js
- site/src/routes/pins-list.js
- website/lib/api.js
- website/pages/files.js
- website/pages/manage.js
- website/pages/new-file.js
- website/pages/new-key.js
> feat: files pagination UI

- website/components/layout.js
- website/lib/magic.js
- website/lib/user.js
- website/pages/callback.js
> fix: safari login

- .github/workflows/api.yml
- .github/workflows/deploy.yml
- README.md
- site/package.json
- site/src/bindings.d.ts
- site/src/constants.js
- site/src/index.js
- site/src/models/users.js
- site/src/routes/tokens-create.js
- site/src/routes/tokens-delete.js
- site/src/routes/tokens-list.js
- site/src/utils/debug.js
- site/src/utils/router.js
- site/src/utils/utils.js
- site/tsconfig.json
- site/webpack.config.js
- site/webpack.config.prod.js
- website/components/navbar.js
- website/next.config.js
- website/package.json
- website/sentry.client.config.js
- website/sentry.server.config.js
> feat: add basic error tracking and fixes user not found issue

- .github/workflows/api.yml
- .gitignore
- site/src/bindings.d.ts
- site/src/errors.js
- site/src/index.js
- site/src/jobs/nfts-index.js
- site/src/jobs/pins.js
- site/src/models/users.js
- site/src/routes/login.js
- site/src/routes/nfts-check.js
- site/src/routes/nfts-delete.js
- site/src/routes/nfts-get.js
- site/src/routes/nfts-list.js
- site/src/routes/nfts-store.js
- site/src/routes/nfts-upload.js
- site/src/routes/pins-add.js
- site/src/routes/pins-delete.js
- site/src/routes/pins-get.js
- site/src/routes/pins-list.js
- site/src/routes/pins-replace.js
- site/src/routes/tokens-create.js
- site/src/routes/tokens-delete.js
- site/src/routes/tokens-list.js
- site/src/utils/auth.js
- site/src/utils/router.js
- site/src/utils/utils.js
> fix(api): improve error handling and sentry capture

- site/src/cluster.js
- site/src/routes/nfts-store.js
`Size` comes back as `0` for non-UnixFS data so use `Bytes` instead.
> fix: dag size for metadata

- packages/website/pages/manage.js
resolves https://github.com/ipfs-shipyard/nft.storage/issues/140
> feat: add API key copy button

- packages/api/package.json
- yarn.lock
See release notes for context https://github.com/nftstorage/ipfs-cluster/releases/tag/v3.0.1
> chore: update cluster dep

- packages/api/package.json
- packages/api/src/models/users.js
- packages/api/src/utils/auth.js
- packages/api/src/utils/jwt.js
- packages/api/test/mocks/cluster/post_add.js
- packages/api/test/nfts-check.spec.js
- packages/api/test/nfts-upload.spec.js
- packages/api/test/scripts/constants.js
- packages/api/test/scripts/worker-globals.js
- packages/api/test/version.spec.js
- yarn.lock
* Adds a mock cluster server using [smoke](https://npm.im/smoke)
* Adds a test that uploads a file, ensures the response is correct and checks it was added to the NFTS and PINS stores
* Minor changes to the JWT utility module to allow it to be used in tests
> test: add test for uploading a single file

- packages/client/src/lib.js
- packages/website/public/schema.yml
> fix: misc docs issues

- packages/client/examples/browser/car/main.js
> fix: car upload example

- packages/website/pages/index.js
Per https://github.com/protocol/nft-website/issues/16 and @atopal, this PR adds a link to [NFT School](https://nftschool.dev) in this site's FAQ section.
Thanks!
> feat: add link to NFT School in FAQ

- packages/client/src/lib/interface.ts
I'm a ts-noob, but this feels like something we could test. Is there a way we can check the interface is complete in CI?
License: MIT
> fix: add storeCar to client interface.ts

- packages/api/src/models/deals.js
The value "null" was found in the DB and parses to `null`. This PR checks the parsed value is not `null` also.
> fix: null deals

- .github/workflows/niftysave-cron-pin.yml
- packages/api/package.json
- packages/cron/package.json
- packages/database/package.json
- packages/niftysave/.repl.js
- packages/niftysave/package.json
- packages/niftysave/src/cluster.js
- packages/niftysave/src/import-asset.js
- packages/niftysave/src/import-metadata.js
- packages/niftysave/src/util.js
- packages/tools/package.json
- yarn.lock
This pull request addresses the problem with certain pin requests getting no response from cluster as per https://github.com/protocol/bifrost-infra/issues/1335.
Changes here:
1. Improve logs so it's easier to identify where things get clogged.
2. Timeouts are introduced to abort requests that take too long.
They also depend on
- https://github.com/nftstorage/ipfs-cluster/pull/8
> fix occuring pin job failures in niftysave

- packages/api/src/cluster.js
- packages/api/src/constants.js
- packages/api/src/routes/nfts-store.js
- packages/api/src/routes/nfts-upload.js
Also applies local add in a bunch of places where we didn't already.
> fix: temporarily locally add all uploads

- .github/workflows/migration-2021-08-18.yml
- packages/database/src/config.js
- packages/database/src/migrations/2021-08-18-token-asset-queue.js
Turns migration into a CRON job
> feat: turn migration into cron job

- packages/client/test/importer.js
- packages/website/next-env.d.ts
- packages/website/public/schema.yml
- yarn.lock
there was a syntax error in the open api schema
closes #348
> fix(website): fix api docs error

- packages/website/pages/files.js
- Closes https://github.com/ipfs-shipyard/nft.storage/issues/364
Demo:  
https://user-images.githubusercontent.com/24696635/132254598-bcfc77d1-1a55-4277-96ac-56156e862105.mov
> feat: links to metadata.json depending on type

- packages/website/components/hero.js
https://user-images.githubusercontent.com/2353186/133119417-d4e9fc15-913f-492b-a4ed-7800c487b9f2.mp4
https://user-images.githubusercontent.com/2353186/133119431-69eaedbb-8905-44ae-8ac4-7d2a01c144f4.mp4
> fix: remove id from getting started CTA link

- package.json
to build-all to prevent CI conflict on service slike heroku
> fix: change conventional build script 

- packages/website/pages/index.js
> feat: add more questions to the FAQ

- packages/website/components/alert.js
- packages/website/components/navbar.js
- packages/website/icons/cross.js
- packages/website/pages/new-file.js
- packages/website/styles/global.css
- ➕ Added an "Alert" component that allows messages to be shown on the top/bottom of the page.
- ⏲️ This component has a built-in timer that animates it when appearing/leaving.
- 💬 This component design details is being discussed in the public discussion (Discord/Slack at the #nft-storage channel)
Closes #404
https://user-images.githubusercontent.com/24696635/133646543-e11098c0-6bcc-42b4-a9c3-6f36de10fb8e.mov
> feat: handle errors in the files page

- packages/niftysave/src/migrate/resource.js
Handles records that do not have `statusText` field
> fix: resource migration

- packages/niftysave/src/migrate/erc721-import.js
Do not fail on duplicates just update dates
> fix: erc721-import migration

- .github/workflows/release.yml
port of https://github.com/web3-storage/web3.storage/pull/489
> chore: add chores and refactors to the changelog

- packages/website/pages/index.js
> feat: add more info to the homepage

- packages/api/src/errors.js
- packages/api/src/utils/db-client.js
Responds with "Database error" to the user and logs the gory details with Sentry.
> feat: db error reporting

- packages/api/src/errors.js
- packages/api/src/utils/db-client.js
- packages/tools/cf-sync/push-to-db.js
- yarn.lock
Moves db error into the client to make it reusable
Avoids duplicate cidv0/v1 in the push pipeline for content and pins
> fix: fix db error and avoid duplicate cids

- .github/workflows/cron-dagcargo-sizes.yml
- .github/workflows/cron-dagcargo-views.yml
- .github/workflows/cron-metrics.yml
- .github/workflows/cron-pinata-v1.yml
- .github/workflows/cron-pinata.yml
- .github/workflows/cron-pins-v1.yml
- .github/workflows/cron-pins.yml
This simply adds interface in github action for dispatching actions via button and allows you to pick a non main branch.
> chore: add manual dispatch to cron jobs

- packages/website/pages/index.js
> chore: content update on homepage about section to link to nft school

- packages/api/db/tables.sql
This PR adds annotations to the DB schema file to provide explanations of the types, tables and values.
> docs: db schema annotations

- packages/niftysave/src/ingest/cursor.js
> fix: update the cursor in both spots

- .prettierignore
- Procfile
- packages/api/src/bindings.d.ts
- packages/api/src/utils/context.js
- packages/api/src/utils/router.js
- packages/database_v2/metadata/databases/default/tables/public_erc721_token_ingestion_queue.yaml
- packages/database_v2/metadata/databases/default/tables/tables.yaml
- packages/database_v2/migrations/default/1636399732590_ingestion_flat_table/down.sql
- packages/database_v2/migrations/default/1636399732590_ingestion_flat_table/up.sql
- packages/niftysave/gen/hasura/zeus/const.js
- packages/niftysave/gen/hasura/zeus/index.d.ts
- packages/niftysave/gen/hasura/zeus/index.js
- packages/niftysave/package.json
- packages/niftysave/scripts/generate-hasura.sh
- packages/niftysave/src/ingest-queue.js
- packages/niftysave/src/ingest/repo.js
(This is still in progress, not ready for a review)
- adds a migration in hasura: a table with no fk relationships and no logging and the ability to use actual batch inserts for optimized write speed
- regenerates hasura zeus-graphql
- pulls the zeus script into a scripts dir
- small changes to the prettierrc so it doesn't try to format .sh/.sql files
> In Progress: Feat/erc721 write-table

- packages/api/src/routes-v1/nfts-upload.js
> fix: cluster local add threshold

- Procfile
- packages/niftysave/src/ingest-queue.js
- packages/niftysave/src/ingest/cursor.js
adds to the work on #727 
- corrects the cursor on the ingest queue
- adds more procs to get records more quickly
> Feat(niftysave): erc721 ingest queue cursor

- Procfile
somewhat short-term mitigation of the downsides of #774. part of #727
> fix (niftysave): subdivides 2021 into more processes

- packages/api/wrangler.toml
I managed to get my local environment setup, though it was a bit of a slog…
I’ll add some notes about the process to #695 in a bit.
> chore: add local env for yusef to wrangler.toml

- packages/website/pages/files.js
- Adds "first" button to pagination
Closes #368 
**Note:** Adding "last" button to be revisited when other, breaking api changes are happening.
> feat: improved pagination for files

- packages/website/pages/faq/faqContent.js
- packages/website/pages/faq/index.js
- packages/website/pages/index.js
> feat: faq-toc

- packages/client/package.json
> fix: add interface.ts to fix docs

- packages/website/lib/faqContent.js
- packages/website/pages/faq.js
* fix for cloudflare build error
> fix: toc-fix

- packages/client/README.md
refs https://github.com/nftstorage/nft.storage/issues/861
refs https://github.com/nftstorage/nft.storage/issues/855
> docs(client): make the example runnable and add note on ESM

- packages/api/scripts/cli.js
- packages/website/next-sitemap.js
- packages/website/next.config.js
- packages/website/package.json
- packages/website/sentry.client.config.js
- packages/website/sentry.server.config.js
- yarn.lock
- adds stack trace linking
- adds performance tracing to the website
- better sourcemaps
- commit tracking
- better versioning for sentry releases
- add distribution config (sentry parses releases better if all the config is there)
- website sentry config improved overall
- fixes cloudflare pages deploy command and sitemap not being generated
closes #858
> feat: improve sentry github integration

- packages/website/components/button.js
- packages/website/components/navbar.js
fixes the way the mobile menu looks in safari
> fix (website): safari buttons for mobile menu

- packages/website/components/blog/cards.js
- packages/website/pages/blog/index.js
- packages/website/styles/blog.css
Addresses some issues in #912 
- Title link leads to blog article when you click it
- include the spotlighted article below in the list (do not exclude it by default)
> feat: blog cleanups

- packages/infra/heroku/grant-postgrest.sql
Oops - forgot to grant access to the cargo schema to nft_storage user 🤦‍♂️
> fix: missing grants

- packages/website/pages/new-file.js
- packages/website/styles/fonts.css
- packages/website/styles/vars.css
Update Copy: warnings and info for file uploads
Fix #856
> feat: Update Copy: warnings and info for file uploads

- packages/website/components/blog/cards.js
- packages/website/components/button.js
- packages/website/components/tags.js
- packages/website/pages/blog/index.js
- packages/website/pages/blog/post/[slug].js
> fix: fix button text color

- packages/website/pages/index.js
- packages/website/styles/about.css
chore: update copy based on dchoi's feedback
Fixes #893
> chore: update copy based on dchoi's feedback

- .github/workflows/cron-pins.yml
Missed while cleaning up v1 bits.
> fix: start command for pins cron job

- .github/workflows/cron-pinata.yml
> fix: pinata cron command

- README.md
- packages/website/README.md
- packages/website/pages/faq.js
Basically trying to codify @dashcraft's process of using the staging build to debug ui.
> fix: document a way to do frontend dev if your environment is not set up.

- packages/website/lib/countly.js
- packages/website/next.config.js
- packages/website/package.json
- packages/website/pages/_app.js
- yarn.lock
- countly is now loaded async from cdn
- swagger updated to fix react errors
- bundle analyser added
> fix: load countly async and update swagger

- packages/website/posts/2021-12-14-storage-layer-maximalism.mdx
* use url instead of relative path for blog thumbnail.
> fix: blog-share

- packages/website/components/blog/cards.js
- packages/website/styles/blog.css
Move img to be child of parent, add a container for padding, move opacity to img and not parent div.
fixes #976
> chore: Issue 976 parent opacity affecting child divs

- packages/website/lib/faqContent.js
- packages/website/package.json
- packages/website/pages/faq.js
Fixes #879 
Updated faq to address skypack and webpack 4 issue.
> chore: Updated faq to address skypack and webpack 4 issue

- packages/website/pages/new-file.js
feat: Remove link to Pinning Service API doc
Closes #988
> feat: Remove link to Pinning Service API doc

- packages/client/examples/browser/storeDirectory.html
Token is not set, and other examples don't use it. So I just removed it here as well.
> fix: store directory example

- packages/website/components/copyButton.js
- packages/website/icons/copy.js
- packages/website/package.json
- packages/website/pages/files.js
- packages/website/styles/button.css
Uses existing copy-to-clipboard package to copy cid to clipboard for easier copying and pasting of cid.
Fixes #969
> feat: add copy icon to files for copying cid

- packages/api/src/middleware/psa.js
Fixes the error given to an unauthorized PSA user.
> fix: error message for unauthorized PSA user

- packages/website/lib/faqContent.js
- packages/website/pages/faq.js
- packages/website/public/schema.yml
> fix: remove confusing language about 100MB uploads

- packages/website/posts/2022-01-05-mikeal-modern-finance.mdx
> feat: mikeal modern finance blog post

- .github/workflows/gateway.yml
- .github/workflows/release.yml
- packages/gateway/README.md
- packages/gateway/package.json
- packages/gateway/scripts/cli.js
- packages/gateway/src/error-handler.js
- packages/gateway/src/index.js
- packages/gateway/test/index.spec.js
- yarn.lock
> feat: add sentry to gateway

- packages/website/pages/docs/concepts/car-files.md
- packages/website/pages/docs/concepts/meta.json
- packages/website/pages/docs/how-to/meta.json
- packages/website/pages/docs/how-to/mint-custom-metadata.md
- packages/website/pages/docs/how-to/mint-erc-1155.md
- packages/website/pages/docs/index.md
- packages/website/pages/docs/why-nft-storage.md
Hey @dashcraft, just putting this up as a PR to your branch for #1044, since I didn't want to push to your branch without asking first :) 
This just replaces the `:::tip` blocks and so on with nextra's `Callout` component.
> chore: formatting tweaks for nextra docs

- packages/api/README.md
- packages/api/db/tables.sql
- packages/api/src/bindings.d.ts
- packages/api/src/constants.js
- packages/api/src/utils/db-client.js
- packages/api/src/utils/db-types.d.ts
- packages/api/test/nfts-store.spec.js
- packages/api/test/nfts-upload.spec.js
- packages/cron/src/bin/pins.js
- packages/cron/src/jobs/pinata.js
- packages/cron/src/jobs/pins.js
- packages/cron/src/lib/utils.js
> fix: move to cluster3

- packages/api/src/errors.js
- packages/api/src/middleware/maintenance.js
- packages/api/src/utils/auth.js
- packages/api/src/utils/db-client.js
- packages/api/test/db-client.spec.js
- yarn.lock
This shoud catch more errors and avoid sending them to sentry.
Includes sentry, maintenance and db errors.
closes #986
> fix: catch more errors

- .github/workflows/cron-pins-failed.yml
- .github/workflows/cron-pins.yml
- README.md
I forgot to add the env vars to the workflows 🤦‍♂️
> fix: pins cron env vars

- packages/cron/package.json
- packages/cron/src/jobs/pins.js
This PR updates the pin status sync cron job to add concurrency and speed up processing.
> perf: concurrent pin status sync

- packages/website/pages/files.js
There was an issue where a typeo didn't access the right key.
Fixes #1108
> fix: quick fix for typeo

- packages/gateway/README.md
- packages/gateway/package.json
- packages/gateway/src/env.js
- packages/gateway/src/error-handler.js
- packages/gateway/src/logs.js
- packages/gateway/wrangler.toml
Adds gateway logs to logtail based on [API work](https://github.com/nftstorage/nft.storage/pull/860)
Needs:
Closes #1036
> feat: gw log tail

- packages/gateway/src/env.js
- packages/gateway/src/index.js
- packages/gateway/src/logs.js
https://github.com/nftstorage/nft.storage/pull/1037 was incomplete and needs to wrap request with log calls
> fix: logtail to log request start and end

- packages/infra/heroku/init.sh
With the previous changes to update this setup to pgrest v9, staging DB is now in the pgrest app. Let's update the script
> fix: heroku staging db location within pg rest app

- packages/website/components/copyButton.js
- packages/website/icons/copy.js
- packages/website/pages/files.js
Updating to use 2 copy buttons, one for cid and the other for IPFS URL with option for redirect.
This will be consistent with new large file uploader designs.
> feat: making changes to the copy options per new designs

- .github/workflows/api.yml
- .github/workflows/release.yml
- yarn.lock
This PR adds release please to the API ci workflow. This setup will only create release PR for API changes and will also enable serial release PR merges.
More PRs will be created for the other packages that need release-please.
> chore: upgrade release ci for API

- packages/gateway/docker/docker-compose.yml
- packages/gateway/package.json
- packages/gateway/scripts/cli.js
- packages/gateway/test/cids.spec.js
- packages/gateway/test/constants.js
- packages/gateway/test/fixtures/directory/path
- packages/gateway/test/index.spec.js
- packages/gateway/test/metrics.spec.js
- packages/gateway/test/mocks/cf-ipfs.com/get_ipfs#@cid.js
- packages/gateway/test/mocks/ipfs.io/get_ipfs#@cid.js
- packages/gateway/wrangler.toml
- yarn.lock
This PR runs a docker container with a go-ipfs node to act as gateway. In the startup, it will add some files to the node for being able to fetch the CIDs in the tests
Closes #1091
> chore: improve gateway tests mocking

- README.md
- packages/api/README.md
- yarn.lock
This PR and the new simple dev setup should be enough to close #472
closes #472
> chore: improve docs for docker

- packages/gateway/package.json
- packages/gateway/wrangler.toml
- yarn.lock
Also simplifies `wrangler.toml` to have unique entry for Durable Objects
> fix: update gateway miniflare to final version

- packages/gateway/src/metrics.js
Prometheus is failing because comments were made in types line
> fix: metrics types

- packages/api/src/routes/pins-list.js
- packages/api/src/utils/db-client-types.ts
- packages/api/src/utils/db-client.js
- packages/api/test/pin-list.spec.js
> fix: pinning api list only returns pin requests

- packages/website/posts/2022-01-25-what-am-buying.mdx
Initial draft of this article. was at https://www.notion.so/protocollabs/When-you-buy-an-NFT-what-are-you-actually-getting-dbc31c3285a34076a85a338830d87601
> feat: blog post When you buy an NFT, what are you actually getting?

- packages/website/pages/files.js
- packages/website/styles/table.css
Truncate providers to 3, with toggle and max-width for remaining providers.
https://user-images.githubusercontent.com/1189523/152860884-d1e2fd88-47e6-4279-af4a-dd42be2c0f18.mov
> feat: limit 3 storage providers and add toggle for showing rest

- packages/website/pages/files.js
Makes the mouse shot the pointer finger when hovering over this control. Previously it did not look like you could click it when hovering.
> fix: add pointer to hidden deals link

- packages/gateway/src/durable-objects/summary-metrics.js
- packages/gateway/src/index.js
- packages/gateway/wrangler.toml
Resets again all migrations to start a clean state to production
> fix: reset gateway durable objects migrations

- packages/api/src/bindings.d.ts
- packages/api/src/constants.js
- packages/api/src/index.js
- packages/api/src/routes/ipfs-get.js
- packages/api/src/utils/logs.js
- packages/api/src/utils/router.js
- packages/api/test/ipfs-get.spec.js
- packages/api/test/scripts/worker-globals.js
- packages/api/wrangler.toml
Add ipfs route to proxy CIDv0 to the gateway
Closes #1049 
Needs:
> feat: api ipfs path

- packages/gateway/src/index.js
> feat: gateway add support for head request

- packages/website/components/inline-code.js
> fix: mobile layout break faq page

- packages/gateway/src/error-handler.js
- packages/gateway/src/errors.js
- packages/gateway/test/index.spec.js
> feat: gateway known errors render html response

- packages/api/db/tables.sql
* Also adding a reason field on the user_tag table.
> Adding ACCOUNT_ENABLED user_tag_type to support blocking/unblocking a user

- packages/website/styles/nextra-theme.css
> fix: remove top level and only entry point via css

- packages/api/src/routes/pins-list.js
- packages/api/test/pin-list.spec.js
> fix: psa list empty

- PEERS
Updates nft3 peers list.
@alanshaw should we remove the older clusters, or is there still value in keeping their info?
> fix: peers list

- packages/website/components/blog/cards.js
- packages/website/styles/blog.css
removed unneeded breakpoint styles, adjusted some of the set height rules to allow the full title to always display.
https://user-images.githubusercontent.com/1189523/155245488-b5823afe-4c4f-48fd-ad37-0abfb8f03045.mp4
> fix: refactor blog highlight

- .gitignore
- .prettierignore
Updates .prettierignore to include sitemap.xml & robots.txt
Closes #1351
> chore: update prettier ignore

- packages/website/components/blog/cards.js
- packages/website/components/loading.js
- packages/website/components/navbar.js
- packages/website/pages/index.js
- packages/website/pages/manage.js
- packages/website/public/spinner.svg
- packages/website/styles/about.css
- packages/website/styles/animations.css
- packages/website/styles/blog.css
- packages/website/styles/nav.css
> fix: front end bugs

- .github/ISSUE_TEMPLATE/config.yml
- packages/website/components/footer.js
- packages/website/pages/docs/troubleshooting.md
> fix: add issue template and discord link to docs

- .github/workflows/gateway.yml
- packages/gateway/package.json
- packages/gateway/scripts/cli.js
- packages/gateway/src/env.js
- packages/gateway/wrangler.toml
Copying  @olizilla 's lovely work from web3 https://github.com/web3-storage/web3.storage/pull/1024 and https://github.com/web3-storage/web3.storage/pull/1033
> fix: gateway sentry source maps

- packages/website/components/layout.js
- packages/website/components/navbar.js
- packages/website/components/types.d.ts
- packages/website/lib/magic.js
- packages/website/lib/user.js
- packages/website/pages/_app.js
- packages/website/pages/index.js
Save to local storage and check before reissuing request to magic auth. If we want, we can manually refresh in the background, but if a user has already auth'd we shouldn't be issuing a request on every render.
I also drastically simplified the redirect logic and the nested layout logic to be much slimmer.
Fixes #1349
> Massively overhauled the user authentication

- packages/website/components/layout.js
- packages/website/components/navbar.js
- packages/website/components/types.d.ts
- packages/website/lib/magic.js
- packages/website/lib/user.js
- packages/website/pages/_app.js
- packages/website/pages/index.js
Reverts nftstorage/nft.storage#1422
> Revert "Massively overhauled the user authentication"

- packages/website/components/layout.js
- packages/website/components/navbar.js
- packages/website/components/types.d.ts
- packages/website/lib/magic.js
- packages/website/lib/user.js
- packages/website/pages/_app.js
- packages/website/pages/index.js
> feat: authentication persistence refactor

- packages/client/src/gateway.js
- packages/client/test/gateway.spec.js
- packages/client/test/lib.spec.js
Closes https://github.com/nftstorage/nft.storage/issues/1345
> fix: gateway url in client

- packages/website/pages/files.js
> fix: website gateway url

- packages/api/src/routes/nfts-upload.js
We currently don't add structure metadata complete when we receive small CAR uploads. Given we already iterate the blocks, we can also go through the DAG and gather more information on whether the CAR is complete.
If we want to rely on this metadata for gateway read test, it would be great to have it here.
> fix: augment car start to inspect car and check if complete

- packages/website/pages/index.js
> feat: add homepage link to decentralization post

- packages/website/pages/files.js
- packages/website/styles/utils.css
closes #1513 
/files page fixes
- corrects capitalization of "CID"
- hides survey until after load and moves to beneath table
> fix: files page fixes

- packages/website/pages/login.js
> fix: fix broken login page styles

- packages/gateway/src/ipfs.js
- packages/gateway/test/ipfs-path.spec.js
Fixes errors detected on:
- https://sentry.io/organizations/protocol-labs-it/issues/3060750504/?project=6097112&query=is%3Aunresolved
- https://sentry.io/organizations/protocol-labs-it/issues/3060634872/?project=6097112&query=is%3Aunresolved
> fix: gateway ipfs path error on invalid cid

- packages/website/next.config.js
- packages/website/pages/docs/concepts/gateways.md
- packages/website/pages/docs/how-to/retrieve.md
This will close #1217, but it needs some more meat on the bones. I'll try to wrap it up for review on Monday.
> feat(docs): add gateway concept doc & update retrieval doc

- packages/cron/src/jobs/pins.js
This PR introduces a grace period for _new_ pins that are reported by cluster to be in `PinError`.
Pins will not transition to `PinError` until they are >24h old and will instead be set to `Pinning`.
Please see [this comment](https://github.com/nftstorage/nft.storage/issues/1484#issuecomment-1061685596) for the context behind this change.
resolves https://github.com/nftstorage/nft.storage/issues/1484
> feat: grace period for new pins found in error state

- packages/website/components/trustedByLogos.js
- packages/website/components/types.d.ts
- packages/website/pages/index.js
- packages/website/pages/stats.js
There is an issue with logos on latest stats branch, refactored trusted by logos to container root dir.
> feat: quick fix for logo issue

- packages/website/pages/stats.js
Add back logos to equal same as frontpage, there's another ticket to add 2 missing logos, this just
brings it up to samesies.
> fix: add back all the same logos as was on the homepage

- packages/website/pages/stats.js
- packages/website/styles/stats.css
Reverts nftstorage/nft.storage#1608
> Revert "fix: stats page"

- packages/website/styles/decorators.css
- packages/website/styles/vars.css
New global hover also accounts for a bit of offset to keep the button centered despite change in hover direction.
https://user-images.githubusercontent.com/1189523/156623765-d1aafe3b-8589-4089-8e80-d530f28caeab.mov
> fix: update global button hover so button drops toward shadow

- packages/api/src/index.js
Stats throws a cors error, i believe I need to add the postcors handler to the route, similar to the other publicly accessible routes.
> feat: add cors handler to stats route, trying to resolve cors issue

- packages/gateway/README.md
Adds gateway architecture overview
> docs: add gateway architecture overview

- packages/website/lib/__tests__/statsUtils.test.js
- packages/website/lib/statsUtils.js
- packages/website/pages/stats.js
Super quick, stats needs to use stats.data to pull data from API.
> fix: stats requires data attr

- packages/website/components/navbar.js
- packages/website/pages/_app.js
- packages/website/pages/index.js
- packages/website/theme.config.js
Fixes #1565 removed useLayoutEffect, useEffect seems to work just as well.
Fixed other lint errors:
1) wherever it was sane not to include functions in dep array for hooks, disabled lint rule, I don't like this rule at all personally
2) Assigned theme to a variable before exporting.
> fix: cleaned up eslint errors

- .github/ISSUE_TEMPLATE/config.yml
uses service for opening mailto link via http
> fix: use mailxto for mailto link

- packages/website/styles/nextra-theme.css
Add toggle for open/close to improve ux on buttons compared to links.
> feat: add ux for button compared to link in docs nav

- packages/website/styles/nextra-theme.css
This should do it.
https://user-images.githubusercontent.com/1189523/157088689-57b21a42-8c91-42a7-a8d9-e2eec6dc260c.mov
> fix: ios z-index and fixed position glitch

- packages/api/db/tables.sql
its already in staging, can you please validate because we need to drop the view completely and recreate
> Making token_id text in the admin_search view

- packages/website/pages/files.js
- packages/website/pages/manage.js
- packages/website/styles/global.css
- packages/website/styles/table.css
- packages/website/styles/tooltip.css
> feat: issue 1642 pin req email hover

- packages/website/pages/files.js
> fix: update /files tooltip copy

- packages/client/src/lib.js
Replaces the import candidate `content` property with a getter function that allows the stream to be created (and file descriptor opened) only when it is accessed.
The issue is that when there are many thousands of files in a directory, we'll attempt to open that many file descriptors eagerly, which can cause `EMFILE` errors on some systems.
refs https://github.com/nftstorage/nft.storage/issues/1672
> fix: create stream when needed

- packages/website/pages/files.js
> fix: revert website gateway to nftstorage.link

- .github/workflows/website.yml
- packages/website/tests/homepage.e2e.spec.ts
* note target branch is issues/1688-screenshots
* because I want to test the gh action before merging into there while in review
> test: add homepage.e2e test that saves screenshot homepage.png

- .github/workflows/gateway.yml
Currently failing because wrangler action is using Node.js 12.
https://github.com/nftstorage/nft.storage/runs/5774601148?check_suite_focus=true
> fix: gateway build with wrangler

- .github/workflows/cron-denylist.yml
> feat: add deny list sync cron job

- .github/workflows/cron-denylist.yml
Runs every 5h and on merge our denylist.json to main.
> refactor: deny list sync schedule

- packages/website/posts/2022-04-04-missing-nfts.mdx
making my author name the same across all posts
> fix wording and author name

- packages/website/next.config.js
- packages/website/pages/docs/how-to/meta.json
- packages/website/pages/docs/how-to/pinning-service.md
Fixes #1026 adds pinning service api doc to the nft storage docs website.
> feat: Updated to add docs for pinning services api

- packages/website/posts/2022-04-05-announcing-nftup.mdx
update blog post for latest build. once this is merged I can work the deploy steps.
> docs: blog post links to beta build

- packages/api/src/constants.js
- packages/api/src/routes/nfts-store.js
- packages/api/src/routes/nfts-upload.js
Same as https://github.com/web3-storage/web3.storage/pull/1241 to go together with https://github.com/nftstorage/nft.storage/pull/1789
> fix: api add to cluster always with local false

- packages/website/pages/docs/how-to/pinning-service.md
We are clarifying based on a user question via @jnthnvctr
> fix: remove confusing verbiage

- packages/api/package.json
- yarn.lock
fixes https://github.com/nftstorage/nft.storage/runs/6094604407?check_suite_focus=true#step:6:19
> fix: pin magic admin

- packages/api/db/migrations/001-add-HasSuperHotAccess-user_tag.sql
- packages/api/db/tables.sql
This PR adds `HasSuperHotAccess` user tag to allow us to grant access to super hot feature as specified in [design document](https://www.notion.so/Technical-Design-MVP-df1fa96cfca04b4daa07218972db3450?d=f646c8ab1b3147deae9758c2a854ed0c#df775820fc8a4f898319f77487a64a78)
Also adds migrations directory similarly to what we do in web3 side
> feat: add HasSuperHotAccess user tag

- packages/website/components/mdx/arch-switch.js
- packages/website/package.json
- packages/website/pages/docs/how-to/meta.json
- packages/website/pages/docs/how-to/nftup.md
- packages/website/pages/docs/quickstart.md
Fixes #1826
This PR
- Created a new docs page for NFTUp
- Adds NFTUp info to the quickstart page.
- Adds a new component `arch-switch` allowing to show install links for current OS.
> feat: nft up docs

- packages/website/next.config.js
There was an issue with nftup route, needs redirect rules, fixed. Should work on deploy preview as well.
> fix: updated nftup route

- packages/api/README.md
- packages/api/src/utils/db-types.d.ts
Fixes #1580 
Re-ran db-types and added documentation for the db-types command for posterity.
> fix: update db-types and add documentation

- packages/api/src/routes/user-tags.js
Adds super hot access tag to the new /user/tags endpoint
> feat: add super hot access tag to user tags endpoint

- packages/website/pages/docs/how-to/store-directory.md
This fixes the `storeDirectory` example script, which was passing the `pathPrefix` and `hidden` options in the wrong place :(
It also adds a call to `path.resolve`, since it seems that `getFilesFromPath` uses the absolute file path, so we need to expand relative paths to get the right prefix removed.
> chore: fix broken storeDirectory pathPrefix example

- packages/api/pw-test.config.cjs
- packages/api/scripts/cmds/db.js
Makes the console a bit more noisy but it is super helpful for when the process hangs.
These were hanging for me - I added this and it turns out docker was just taking ages to download images. I didn't know that was happening so I didn't wait around for it to finish.
> chore: inherit stdio

- packages/website/pages/docs/troubleshooting.md
@mishmosh Update Module Not Found FAQ to include info on Nest JS/Jest fix.
> docs: Update troubleshooting.md

- packages/website/lib/countly.js
- packages/website/pages/files.js
- packages/website/pages/index.js
Fixes: #1779
This PR adds a button link from the files page to the NFTUp docs page.
> feat: add nftup link on files page

- packages/api/db/reset.sql
This is for local dev purposes only.  Should not affect any release in any way.
> chore: Fixing local dev by adding DROP TABLE metric to reset.sql

- README.md
> docs: remove missing sections from README

- .github/workflows/cron-dagcargo-sizes.yml
- .github/workflows/cron-metrics.yml
- .github/workflows/cron-pinata.yml
- .github/workflows/cron-pins-failed.yml
- .github/workflows/cron-pins.yml
- .github/workflows/cron.yml
Fixes #1931 
Port of web3.storage [one](https://github.com/web3-storage/web3.storage/pull/1281/files)
> feat: cron release workflow

- packages/api/db/reset.sql
> fix: Adding user_tag_proposal schema to reset.sql for local dev

- .env.tpl
- packages/api/src/bindings.d.ts
- packages/api/src/config.js
- packages/api/src/index.js
- packages/api/src/routes/user-requests.js
- packages/api/src/utils/db-client.js
- packages/api/src/utils/utils.js
- packages/api/test/scripts/globals.js
- packages/website/components/types.d.ts
- packages/website/lib/api.js
- packages/website/lib/countly.js
- packages/website/pages/_app.js
- packages/website/pages/manage.js
- packages/website/pages/pinning-request.js
This replaces the existing mailto links for pinning requests with a form so that the requests can be managed within the admin site.  It also adds a slack notification.
> feat: add support for user requests

- packages/website/posts/2022-06-22-spring-integration-spotlights.mdx
- packages/website/styles/markdown.css
> feat: Q3'22 integration blog post

- packages/api/src/routes/nfts-upload.js
`iterateDag` returns false if the DAG is incomplete, but also if it was unable to decode a block.
If the DAG is not complete, it is not necessarily "partial" we just might have not been able to decode a block.
That function needs to return the DAG structure - `false` is ambiguous. i.e. `false` could be `Partial` or `Unknown`.
This PR renames `iterateDag` to `getDagStructure` which returns the structure as `Complete`/`Partial`/`Unknown`.
> fix: dag structure check

- packages/cron/src/bin/nft-ttr.js
- packages/cron/src/bin/nft-ttr.spec.js
- packages/cron/src/jobs/measureNftTimeToRetrievability.js
- packages/cron/src/jobs/measureNftTimeToRetrievability.spec.js
- packages/cron/src/lib/metrics.js
- packages/cron/src/lib/testing.js
- packages/cron/src/prom-client.d.ts
Motivation:
* https://github.com/nftstorage/nft.storage/issues/1994
* https://github.com/nftstorage/nft.storage/issues/2033
> feat(cron): nft-ttr logs store_duration_seconds to prometheus

- packages/website/package.json
- packages/website/pages/faq.js
- packages/website/tailwind.config.js
- yarn.lock
Added tailwind typography plugin for faq content. Adds the link styles automatically and makes leading a bit easier to read.
> fix: add tailwind typography to faq content.

- packages/website/components/blog/cards.js
- packages/website/components/button.js
- packages/website/components/footer.js
- packages/website/components/link.js
- packages/website/components/navbar.js
- packages/website/lib/faqContent.js
- packages/website/pages/faq.js
- packages/website/pages/index.js
- packages/website/pages/manage.js
- packages/website/pages/new-file.js
allows treating `Link` a little more uniformly, without having to nest anchor tags within them.
> refactor: create a consolidated link component

- package.json
- packages/api/wrangler.toml
- yarn.lock
wrangler needs `no_bundle = true` or else its using its own bundling thing....
> fix: fix error sourcemaps with wrangler

- .github/workflows/website.yml
> fix: website CI secrets

- .github/workflows/website.yml
Did https://github.com/nftstorage/nft.storage/pull/2101 but workflow was not being triggered for changes in this path
> fix: website workflow should trigger when its yml is modified

- PEERS
We can update when the domain name changes.
> docs: add Elastic IPFS

- packages/api/src/utils/db-client.js
* Now that admin.storage will set deleted_at there's no need to handle this in the applications.
> fix: Handling deleted_at on user requests from admin.storage (see nftstorage/admin.storage/issues/92)

- packages/website/pages/manage.js
- packages/website/pages/pinning-request.js
> feat: update pinning request verbiage

- .github/workflows/client.yml
- .github/workflows/create-nft-storage.yml
after we merge this we can delete the repo NPM_AUTH_TOKEN secret
> chore: change npm token var

- packages/website/public/_redirects
This PR adds a cloudflare redirect config file per documentation
> chore: add Cloudflare redirect config file

- .github/workflows/api.yml
- .github/workflows/client.yml
- .github/workflows/create-nft-storage.yml
- .github/workflows/cron.yml
- .github/workflows/website.yml
Closes #2192 
See [identical PR in web3](https://github.com/web3-storage/web3.storage/pull/1316)
> chore: add chores to changelog

- packages/website/pages/docs/how-to/get-status.md
> docs: update status docs

- packages/api/package.json
- packages/api/src/bindings.d.ts
- packages/api/src/config.js
- packages/api/src/utils/car.js
- packages/api/src/utils/context.js
- packages/api/src/utils/uploader/r2-uploader.js
- packages/api/test/config.spec.js
- packages/api/test/nfts-upload.spec.js
- packages/api/wrangler.toml
- yarn.lock
- write a CARv2 index so we can use the `SATNAV` bucket to find where Blocks are.
- write a key to map root CID to car CID so we can use the `DUDEWHERE` bucket to find where our CAR is in `CARPARK` (for a given root CID).
This enables [freeway](https://github.com/web3-storage/freeway) to lookup CAR CID(s) for a given root data CID and UnixFS export data directly from R2.
port of https://github.com/web3-storage/web3.storage/pull/2035
License: MIT
Signed-off-by: Oli Evans <oli@protocol.ai>
> feat: write DUDEWHERE link and SATNAV car indexes.

- packages/website/components/button.js
- packages/website/components/footer.js
- packages/website/components/hashlink.js
- packages/website/components/navbar.js
- packages/website/package.json
- packages/website/pages/_app.js
- yarn.lock
Wire up plausible and keep count.ly while we test this implementation.
> feat: add plausible analytics

- packages/website/components/footer.js
> fix: update footer link to the nftstorage twitter page

- packages/api/wrangler.toml
tryin somethin... (will revert and add more detail if this works)
> fix: enable the `url_standard` compatibility flag

- packages/api/wrangler.toml
maybe there's something funny happening in some shims?
> fix: enabled nodejs compat

- packages/api/src/routes/nfts-upload.js
- packages/api/wrangler.toml
I added these all while debugging upload issues, should be able to remove them now
> fix: remove debugging console.logs and nodejs_compat flag

- packages/website/README.md
mostly want to to trigger a staging deploy but this is good to do anyway
> feat: tweak readme

- packages/website/lib/api.js
> fix: use correct "nft get" endpoint

- packages/api/src/utils/context.js
- packages/api/src/utils/w3up.js
the staging API seems to be trying to get CIDs from the production bucket, debug this
> chore: more deals get debugging
